<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <div id="recurring_buttons_view"><?php echo $this->getButtonsHtml() ?></div>
                <div id="recurring_cancel_button_view" style="display:none;"><?php echo $this->_getCancelButtonWithReasons(); ?></div>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getViewHtml() ?>
<?php /* @var $this Mage_Sales_Block_Recurring_Profile_View */ ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<!-- info tabs -->
<?php $infoTabs = $this->getChildGroup('info_tabs'); ?>

<dl class="order-info">
    <dt><?php echo $this->__('About This Profile:') ?></dt>
    <dd>
        <ul id="order-info-tabs">
            <?php foreach ($infoTabs as $block): ?>
                <?php if ($this->getObjectData($block, 'is_view_current')): ?>
                    <li class="current"><strong><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></strong></li>
                <?php else: ?>
                    <li><a href="<?php echo $this->escapeHtml($this->getObjectData($block, 'view_url')) ?>"><?php echo $this->escapeHtml($this->getObjectData($block, 'view_label')) ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </dd>
</dl>

<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getBackUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Recurring Profiles') ?></a></p>
</div>
</div>
<script type="text/javascript">
    function cancelviewstatus(current_id, change_id)
    {
        document.getElementById(current_id).style.display = 'none';
        document.getElementById(change_id).style.display = 'block';
    }

    function cancel_action(message, url, cancelReason)
    {
        var reason = parseInt(document.getElementById('reason-subscribe').value);
        var resontext = document.getElementById('reason-subscribe');
        var resontextval = resontext.options[resontext.selectedIndex].innerHTML;

        if (reason) {
            if (confirm(message)) {
                window.location.href = url + "?reason=" + resontextval;
            }
        } else {
			alert(cancelReason);
		}
        return false;
    }
</script>