<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$maskedCardInfo = $this->getMethod()->getMaskedCardInfo();
$ccSecure = $this->getMethod()->getConfigData('enable_cc3d');
$ccFormType = $this->getMethod()->getConfigData('cc_form_type');
$oneClickShopping = (!$ccSecure && $this->getMethod()->getConfigData('cc_shop_type') == 1 && $maskedCardInfo) ? 1 : '';
?>

<ul class="form-list" id="payment_form_<?php echo $code; ?>" style="display:none;">
    <!-- Credit Card payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
            <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" class="nnlogo-href">
                <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <?php $imgpath = $helper->getPaymentLogoUrl() . $typeCode . ".png"; ?>
                    <img class="nnlogo-cc-img" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>"
                    title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
                <?php endforeach; ?>
            </a>
        <?php endif; ?>
    </div>
    <!-- Credit Card payment logo -->
    <div class="nnloader" id='cc_loading'
    style="background: url('<?php echo $helper->getPaymentLogoUrl(); ?>novalnet-loading-icon.gif') 50% 50% no-repeat;"></div>
    <!-- Credit Card shopping type link -->
    <div id="cc_oneclick_link" style="cursor:pointer;display:none;">
        <ul>
            <li>
                <span id ='cc_title_new' onclick='formChange("new")' style='color:blue'>
                    <u><b><?php echo $this->__('Enter card details'); ?></b></u>
                </span>
                <span id ='cc_title_given' onclick='formChange("given")' style='color:blue'>
                    <u><b><?php echo $this->__('Given card details'); ?></b></u>
                </span>
            </li>
        </ul>
    </div>
    <!-- Credit Card shopping type link -->
    <!-- Credit Card given form -->
    <div id="cc_oneclick_given">
        <?php if ($oneClickShopping): ?>
            <ul>
                <li>
                    <label><?php echo $this->__('NN CC type') . ': ' . $maskedCardInfo['card_type']; ?> </label>
                </li>
                <li>
                    <label><?php echo $this->__('NN CC holder') . ': ' . $maskedCardInfo['card_holder']; ?> </label>
                </li>
                <li>
                    <label><?php echo $this->__('NN CC number') . ': ' . $maskedCardInfo['cc_no']; ?></label>
                </li>
                <li>
                    <label><?php echo $this->__('NN Expiration Date') . ': ' . $maskedCardInfo['exp_month'] . '/' . $maskedCardInfo['exp_year']; ?></label>
                </li>
                <li>
                    <label for="<?php echo $code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('NN CVC') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $code ?>_cc_cid" name="payment[cc_cid]" value="" onkeypress="return isNumberKey(event);"/>
                        </div>
                        <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                    </div>
                </li>
            </ul>
        <?php Endif; ?>
    </div>
    <!-- Credit Card given form -->
    <!-- Payment description -->
    <div id ='cc_redirect_desc' style='display:none'>
        <?php echo $this->__('redirect payment description')."<br>".$this->__('Please don’t close the browser after successful payment, until you have been redirected back to the Shop'); ?>
    </div>
    <div id ='cc_direct_desc' style='display:none'>
        <?php echo $this->__('The amount will be debited from your credit card once the order is submitted'); ?>
    </div>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo(); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == false): ?>
        <li>
            <div class="nn-mode">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged'); ?>
            </div>
        </li>
    <?php endif; ?>
    <!-- Display the payment mode notification -->
    <!-- Form hidden elements -->
    <input type="hidden" id="cc_oneclick_shopping" name="cc_oneclick_shopping" value="<?php echo $oneClickShopping; ?>" />
    <input type="hidden" id="cc_enter_data" name="cc_enter_data" value="1" />
    <!-- Form hidden elements -->
</ul>
