<?php Mage::helper('sofortueberweisung')->__('Paymentinformations: %s',$this->getMethod()->getTitle()) ?>
{{pdf_row_separator}}
<?php Mage::helper('sofortueberweisung')->__('Paycode: %s',$this->getInfo()->getOrder()->getPayment()->getSuPaycode()) ?>{{pdf_row_separator}}
<?php if($this->getInfo()->getOrder()->getPayment()->getSuTransactionId()): ?>
<?php Mage::helper('sofortueberweisung')->__('Transaction Id: %s',$this->getInfo()->getOrder()->getPayment()->getSuTransactionId()) ?>{{pdf_row_separator}}
<?php endif; ?>
