<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $_code = Novalnet_Payment_Model_Config::NN_CC;
?>
<script type="text/javascript">
function updateHiddenElements(elements) {

    for (var i=0; i<elements.length; i++) {
        switch (elements[i].name) {
            case 'novalnet_cc_owner':
                elements[i].value = document.getElementById('<?php echo $_code ?>_cc_owner').value;
                break;
            case 'novalnet_cc_type':
                elements[i].value = document.getElementById('<?php echo $_code ?>_cc_type').value;
                break;
            case 'novalnet_cc_pan_hash':
                elements[i].value = document.getElementById('nncc_cardno_id').value;
                break;
            case 'novalnet_cc_unique_id':
                elements[i].value = document.getElementById('nncc_unique_id').value;
                break;
            case 'novalnet_cc_exp_month':
                elements[i].value = document.getElementById('<?php echo $_code ?>_expiration').value;
                break;
            case 'novalnet_cc_exp_year':
                elements[i].value = document.getElementById('<?php echo $_code ?>_expiration_yr').value;
                break;
			case 'novalnet_cc_cid':
                elements[i].value = document.getElementById('<?php echo $_code ?>_cc_cid').value;
                break;
        }
    }
    return true;
}
</script>
<!--{{{ Payment Description -->
<ul>
    <li style="margin: 0 0 8px;">
        <?php echo $this->__('The amount will be booked immediately from your credit card.');?>
    </li>
    <li style="margin: 0 0 8px;">
        <?php echo Mage::helper('novalnet_payment')->getModel('novalnetCc')->_getConfigData('booking_reference') ?>
    </li>
    <?php if(Mage::helper('novalnet_payment')->getModel('novalnetCc')->_getConfigData('live_mode', true) == 0): ?>
    <li style="margin: 0 0 8px;">
        <div style="font-weight:bold;color:red;font-size:12px;">
            <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
        </div>
    </li>
    <?php endif ?>
</ul>
<!--}}} Payment Description -->

<!--{{{ Novalnet Iframe -->
    <?php echo Mage::helper('novalnet_payment')->getModel('novalnetCc')->getNovalnetIframe() ?>
<!--}}} Novalnet Iframe -->
