<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
	$code    = $this->getMethodCode();
	$helper  = Mage::helper('novalnet_payment');
?>
<fieldset class="form-list">
    <div>
    <!--{{{ Payment Logo -->
        <a href="<?php echo $helper->getNovalnetUrl();?>" target="_new" style="text-decoration:none;">
            <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl()."/img/ELV_Logo.png";  ?>
            <img style="height:20px;" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
        </a>
    <!--}}} Payment Logo -->
    </div>
    <!--{{{ ELVAT Form -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <!--{{{ Payment Description -->
        <li style="padding-top: 0.5em;">
            <?php echo $this->__('Your account will be debited upon delivery of goods.') ?>
        </li>
        <!--}}} Payment Description -->
        <?php if($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if($this->getLiveMode() == 0): ?>
        <li>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
            </div>
        </li>
        <?php endif ?>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_account_holder"><?php echo $this->__('Account Holder') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_holder" name="payment[account_holder_at]" title="<?php echo $this->__('Account Holder') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_number" name="payment[account_number_at]" title="<?php echo $this->__('Account Number') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_bank_sorting_code"><?php echo $this->__('Bank Code') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_bank_sorting_code" name="payment[bank_sorting_code_at]" title="<?php echo $this->__('Bank Code') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
    </ul>
    <!-- ELVAT Form -->
</fieldset>
