<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
	$code    = $this->getMethodCode();
	$helper  = Mage::helper('novalnet_payment');
?>
<fieldset class="form-list">
    <div>
    <!--{{{ Payment Logo -->
        <a href="<?php echo $helper->getNovalnetUrl();?>" target="_new" style="text-decoration:none;">
            <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl()."/img/ELV_Logo.png";  ?>
            <img style="height:20px;" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
        </a>
    <!--}}} Payment Logo -->
    </div>
    <!--{{{ ELVDE Form -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <!--{{{ Payment Description -->
        <li style="padding-top: 0.5em;">
            <?php echo $this->__('Your account will be debited upon delivery of goods.') ?>
        </li>
        <!--}}} Payment Description -->
        <?php if($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if($this->getLiveMode() == 0): ?>
        <li>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
            </div>
        </li>
        <?php endif ?>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_account_holder"><?php echo $this->__('Account Holder') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_holder" name="payment[account_holder]" title="<?php echo $this->__('Account Holder') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_number" name="payment[account_number]" title="<?php echo $this->__('Account Number') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_bank_sorting_code"><?php echo $this->__('Bank Code') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_bank_sorting_code" name="payment[bank_sorting_code]" title="<?php echo $this->__('Bank Code') ?>" class="required-entry input-text" autocomplete="off" />
            </div>
        </li>
        <!--{{{ ACDC check-->
        <?php if ($this->getAcdc()): ?>
            <li>
                <div class="input-box">
                    <input type="checkbox" id="<?php echo $code ?>_acdc" name="payment[acdc]" title="<?php echo $this->__('acdc') ?>" class="required-entry" />
                    <label style="float:none;" id="elvde_acdc" for="<?php echo $code ?>_acdc"><b><a><?php echo $this->__('Your credit rating is checked by us') ?></a></b>&nbsp;<span class="required">*</span></label>
                </div>
            </li>
			<script type="text/javascript">
				var showbaby;

				//ACDC Info
				 $("elvde_acdc").observe('mouseover', function() {
					var url = parent.location.href;
					url = '<?php echo $helper->getNovalnetPaymentFormLogoUrl(); ?>/img/acdc_info.png';w='550';h='300';x=screen.availWidth/2-w/2;y=screen.availHeight/2-h/2;
					showbaby = window.open(url,'showbaby','toolbar=0,location=0,directories=0,status=0,menubar=0,resizable=1,width='+w+',height='+h+',left='+x+',top='+y+',screenX='+x+',screenY='+y);
					showbaby.focus();
				});

				//Hide ACDC info
				function hide_acdc_info() { showbaby.close(); }
			</script>
        <?php endif ?>
        <!--}}} ACDC check-->
    </ul>
    <!-- ELVDE Form -->
</fieldset>
