<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$assignDatahelper = Mage::helper('novalnet_payment/AssignData');
$sepaRefill = $this->getMethod()->getNovalnetConfig('auto_refill');
$sepaPaymentRefill = $this->getMethod()->getConfigData('sepa_payment_refill');
$refillValues = $assignDatahelper->getCheckout()->getRefilldatavalues();
$refillMethod = ($sepaRefill && $refillValues && $code == $refillValues->getMethod());
// get quote billing address
$billingaddress = Mage::getSingleton('adminhtml/session_quote')->getQuote()->getBillingAddress();
$street = $billingaddress->getStreet();
$customerlogin = Mage::getSingleton('customer/session')->isLoggedIn();
$panhash = '';

if ($sepaPaymentRefill && $customerlogin) {
    $panhash = Mage::getModel('novalnet_payment/separefill')->getSepaPanHash($helper);
} else if ($sepaRefill) {
    $panhash = $assignDatahelper->getCheckout()->getSepaHash();
}
$panhash = (($sepaPaymentRefill || $sepaRefill) && $panhash) ? $panhash : '';
?>
<fieldset class="form-list" id="fieldset_<?php echo $code ?>">
    <!--{{{ Payment Logo -->
    <?php if ($helper->getModel($code)->getNovalnetConfig('enable_payment_logo', true)): ?>
		<div>
			<a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" style="text-decoration:none;">
				<?php
				$image = "sepa.png";
				$imgpath = $helper->getNovalnetPaymentFormLogoUrl() . $image;
				?>
				<img src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
			</a>
		</div>
    <?php endif; ?>	
    <!--}}} Payment Logo -->
    <!--{{{ Novalnet SEPA Form -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <div class="nnsepaloader" id='sepa_loading' style='display:none;'></div>
        <li>
            <?php echo $this->__('Your account will be debited upon the order submission'); ?>
        </li>
        <?php if ($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if (Mage::helper('novalnet_payment')->getModel('novalnetSepa')->getNovalnetConfig('live_mode', true) == 0): ?>
            <li>
                <div style="font-weight:bold;color:red;font-size:12px;">
                    <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
                </div>
            </li>
        <?php endif ?>

        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_account_holder"><?php echo $this->__('Account Holder') ?><span class="required">*</span></label><br/>
                <div class="input-box">
                    <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_account_holder" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" name="payment[account_holder]" autocomplete="off" value="<?php echo $billingaddress->getFirstname() . ' ' . $billingaddress->getLastname(); ?>" />
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_bank_country"><?php echo $this->__('NN Country') ?><span class="required">*</span></label><br />
                <div class="input-box">
                    <?php
                    $_countries = Mage::getResourceModel('directory/country_collection')
                            ->loadData()
                            ->toOptionArray(false)
                    ?>
                    <?php if (count($_countries) > 0): ?>
                        <select id="<?php echo $code ?>_bank_country" onchange="unsetHashRelatedElements()" class="required-entry">
                            <?php
                            foreach ($_countries as $_country):
                                if (in_array($billingaddress->getCountryId(), $_country)) {
                                    ?>
                                    <option selected value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?>
                                    </option>
                                <?php } else { ?>
                                    <option value="<?php echo $_country['value'] ?>">
                                        <?php echo $_country['label'] ?>
                                    </option>
                                <?php } ?>
                            <?php endforeach; ?>
                        </select><br/>
                    <?php endif; ?>
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_account_number"><?php echo $this->__('IBAN or Account number') ?><span class="required">*</span></label><br/>
                <div class="input-box">
                    <input type="text" id="<?php echo $code ?>_account_number" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" title="<?php echo $this->__('IBAN or Account number') ?>" class="required-entry input-text" autocomplete="off" value="" />
                </div>
            </div>
        </li>

        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_bank_code"><?php echo $this->__('BIC or Bank code') ?><span class="required">*</span></label><br/>
                <div class="input-box">
                    <input type="text" id="<?php echo $code ?>_bank_code" title="<?php echo $this->__('BIC or Bank code') ?>" class="input-text" autocomplete="off" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements()" value="" />
                </div>
            </div>
        </li>

        <li class="fields">
            <div class="field">
                <div class="input-box">
                    <input type="checkbox" id="<?php echo $code ?>_mandate_confirm" title="<?php echo $this->__('confirm') ?>" class="required-entry" onclick="generate_sepa_iban_bic(this, '<?php echo $this->__('Your account details are invalid') ?>', '<?php echo $this->__('Basic parameter not valid') ?>')"/>
                    <label style="float:none;" ><?php echo $this->__('NN Confirm') ?><span class="required"></span></label><br/>
                </div>
            </div>
        </li>
    </ul>

    <input id="process_vendor_id" type="hidden" value="<?php echo trim($this->getMethod()->getNovalnetConfig('merchant_id', true)) ?>"/>
    <input id="auth_code" type="hidden" value="<?php echo trim($this->getMethod()->getNovalnetConfig('auth_code', true)) ?>"/>
    <input id="sepaiban" type="hidden" value="">
    <input id="sepabic" type="hidden" value="">
    <input id="sepa_payment_id" type="hidden" value="37">
    <input id="result_mandate_unique" type="hidden" value="" name="result_mandate_unique">
    <input id="nnsepa_iban_confirmed" type="hidden" value="0" name="nnsepa_iban_confirmed">
    <input id="nn_sepa_merchant_validate_error_message" type="hidden" value="<?php echo $this->__('Basic parameter not valid') . '!'; ?>" />
    <input id="nn_sepa_validate_error_message" type="hidden" value="<?php echo $this->__('Your account details are invalid') . '!'; ?>" />
    <input id="result_sepa_hash" type="hidden" value="<?php echo $panhash; ?>" name="result_sepa_hash">
</fieldset>
<style>
.nnsepaloader {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 9999;
  background: url('<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>novalnet-loading-icon.gif') 50% 50% no-repeat;
}
</style>
