<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2012 Novalnet AG
 * @version    1.0.0
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($_info = $this->getInfo()): ?>
<?php if($this->getNnTestorder() || Mage::getSingleton('checkout/session')->getSecureTestOrder()) echo '<div style="color:white;font-weight:bold;background:red;padding:5px 10px;text-align:center;font-size:15px">!',$this->__('Testorder'),'!</div>' ?>
<?php echo $this->__($this->htmlEscape($this->getPaymentMethod())) ?><br />
<?php echo $this->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?><br />
<?php echo $this->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?><br />
<?php echo $this->__('Credit Card Number: %s', $this->htmlEscape($this->getInfo()->getCcNumberEnc())) ?><br />
<?php echo $this->__('Expiration Date: %s/%s', $this->htmlEscape(str_pad('',2,'*',STR_PAD_RIGHT)), $this->htmlEscape(str_pad(substr($this->getInfo()->getCcExpYear(),0,-2),strlen($this->getInfo()->getCcExpYear()),'*',STR_PAD_RIGHT))) ?><br />
<?php echo $this->__('Card Verification Number: %s', '***') ?><br />
<?php if ($_info->getLastTransId()!="")	echo $this->__('TID : %s', $this->htmlEscape($_info->getLastTransId())) ?><br />
<?php else: ?>
<?php endif; ?>
