<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper">
    <table class="data-table" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col width="1" />
        <col width="1" />
        <?php endif; ?>
        <thead>
            <tr>
                <th rowspan="<?php echo $rowspan ?>"><?php echo $this->__('Product Name') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Price') ?></th>
                <th rowspan="<?php echo $rowspan ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                <th colspan="<?php echo $colspan ?>" class="a-center"><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); 
$magento_version=Mage::getVersion();
echo'<input type="hidden" name="magentoversion" id="magentoversion" value="'.$magento_version.'">';
if($magento_version>='1.5')
{
?>
<script type="text/javascript">
    decorateTable('checkout-review-table');
    truncateOptions();
</script>
<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>

	 <div align="right">
	 	<button id="placeorder_button" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="novalnet.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
	</div>

        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
</div>
<?php 
}
else
{ ?>

 <script type="text/javascript">
//<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
	 document.getElementById('checkout-review-submit').style.display='none';	
//]]>
</script>
<div id="checkout-review-submit-novalnet">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container-novalnet">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php //echo $this->getChildHtml('button') ?>

	 <div align="right">
	 	<button id="placeorder_button" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="novalnet.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
	 </div>
        <span class="please-wait" id="review-please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
        </span>
    </div>
</div>
<?php
}	
$session = Mage::getSingleton('checkout/session');
$paymentmethod=$session->getQuote()->getPayment()->getMethodInstance()->getCode();
?>
<script type="text/javascript">
//<![CDATA[
	novalnet = new Novalnet('<?php echo $this->getUrl('checkout/onepage/saveOrder') ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'), '<?php echo $paymentmethod; ?>');
//]]>
</script>

<div id="nn_iframe" style="display:none;">
<?php
	if($paymentmethod=='novalnetCc')
	{
		$_dataObj = Mage::getModel('novalnet/novalnetcc')->getFormData();
		$session->setNovalnetQuoteId($session->getQuoteId())
      		  ->setNovalnetRealOrderId($_dataObj->getInputval1());
		$form = new Varien_Data_Form();
		$html = '<html><body>';
		echo '<form action="https://payport.novalnet.de/pci_payport" id="novalnetCc" name="novalnetCc" method="POST" target="my_iframe">';
		foreach ($_dataObj->toArray() as $field=>$value) {
		$form->addField($field, 'hidden', array('name'=>$field, 'value'=>$value));
		}
		$html.= $form->toHtml();
		$html.="<iframe id='my_iframe' name='my_iframe' width='553' height='385' frameBorder='0'></iframe>";
		$html.= '</form>';
		$html.= '<script type="text/javascript">document.getElementById("novalnetCc").submit();</script>';
		$html.= '</body>';
		echo $html.= '</html>';
	}
?>
</div>

		
