<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$helper = Mage::helper('novalnet_payment');
$vendorScriptUrl = $helper->getUrl('novalnet_payment/callback/');
$scopeId = $helper->getScopeId();
?>
<div>
    <input type="hidden" name="storeId" id="storeId" value="<?php echo $scopeId; ?>" />
    <input type="hidden" name="nn_lang" id="nn_lang" value="<?php echo strtoupper($helper->getDefaultLanguage()); ?>" />
    <input type="hidden" name="nn_server_ip" id="nn_server_ip" value="<?php echo $helper->getServerAddr(); ?>" />
    <input type="hidden" name="nn_vendorscript_url" id="nn_vendorscript_url" value="<?php echo $vendorScriptUrl; ?>" />
    <input type="hidden" name="nn_tariff_id" id="nn_tariff_id" value="<?php echo Mage::getStoreConfig('novalnet_global/novalnet/tariff_id', $scopeId); ?>" />
    <input type="hidden" name="nn_subsTariff_id" id="nn_subsTariff_id" value="<?php echo Mage::getStoreConfig('novalnet_global/novalnet/subscrib_tariff_id', $scopeId); ?>" />
</div>
