<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Novalnet AG
 * @version    1.0.0
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
	$code    = $this->getMethodCode();
	$baseUrl = Mage::getBaseUrl('skin')
?>
<?php if ($this->checkCustomerAccess()): ?>
<fieldset class="form-list">
	<div style="position: relative; left: 14em; top: -2.5em; width:100px;">
			<?php $imgpath = "images/novalnet/ELV_Logo.png";  ?>
			<img src='<?php echo Mage::getDesign()->getSkinUrl($imgpath) ?>' alt='ELV Logo'/>
	</div>
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $code ?>_account_holder"><?php echo $this->__('Account Holder') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_holder" name="payment[account_holder]" title="<?php echo $this->__('Account Holder') ?>" class="required-entry input-text" value="" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $code ?>_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_account_number" name="payment[account_number]" title="<?php echo $this->__('Account Number') ?>" class="required-entry input-text" value="" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $code ?>_bank_sorting_code"><?php echo $this->__('Bank Sorting Code') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_bank_sorting_code" name="payment[bank_sorting_code]" title="<?php echo $this->__('Bank Sorting Code') ?>" class="required-entry input-text" value="" />
            </div>
        </li>
		<?php if($this->acdc_check()): ?>
		<li>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $code ?>_acdc" name="payment[acdc]" title="<?php echo $this->__('acdc') ?>" class="required-entry" />
                <label for="<?php echo $code ?>_acdc"><?php echo $this->__('The') ?> <b><a href='javascript:show_acdc_info()' ONMOUSEOVER='show_acdc_info()'><?php echo $this->__('ACDC-Check') ?></a></b> <?php echo $this->__('accepted') ?> <span class="required">*</span></label>
            </div>
        </li>
		<?php endif ?>
		<?php if($this->show_comment()): ?>
		<li>
            <div class="input-box">
                <?php echo $this->show_comment()?>
            </div>
        </li>
		<?php endif ?>
    </ul>
	<script type="text/javascript">
		var showbaby;
		function show_acdc_info(){
			var url=parent.location.href;
			url='<?php echo $baseUrl?>frontend/default/default/images/novalnet/acdc_info.png';w='550';h='300';x=screen.availWidth/2-w/2;y=screen.availHeight/2-h/2;
			showbaby=window.open(url,'showbaby','toolbar=0,location=0,directories=0,status=0,menubar=0,resizable=1,width='+w+',height='+h+',left='+x+',top='+y+',screenX='+x+',screenY='+y);
			showbaby.focus();
		}
		function hide_acdc_info(){showbaby.close();}
	</script>
</fieldset>
<?php else: ?>
	<script type="text/javascript">
		function hideMe(payment_code){
			t = 'p_method_' + payment_code.toString();
			document.getElementById(t).style.visibility = 'hidden';
			aTags = document.getElementsByTagName("label");
			if (aTags && aTags.length) {
				for (i=0; i<aTags.length; i++){
					if (aTags[i].htmlFor == t){
						aTags[i].style.visibility = 'hidden';
						i = aTags.length;
					}
				}
			}
		}
		<?php echo "hideMe('$code');"; ?>
	</script>  
<?php endif; ?>
