<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$data = $this->getNovalnetTransactionStatus();
?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
<input type="hidden" name="order_id" value="<?php echo $data->getOrderNo() ?>"/>

<div class="box-left">
    <!--Novalnet Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Order Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Store-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getStoreId() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Order ID') ?></label>
                    </td>
                    <td class="label">
                        <?php
                        $orderViewId = Mage::getModel('sales/order')->loadByIncrementId($data->getOrderId())->getId();
                        $orderViewUrl = Mage::helper('adminhtml')->getUrl('adminhtml/sales_order/view', array(
                            'order_id' => $orderViewId));
                        ?>
                        <strong><a href="<?php echo $orderViewUrl ?>"><?php echo $data->getOrderId() ?></a></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Transaction ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getTransactionNo() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Transaction-Status Text') ?></label>
                    </td>
                    <td class="label">
                        <strong>
                            <?php
                            if ($data->getTransactionStatus() == 100) {
                                echo $this->helper('novalnet_payment')->__('Successful');
                            } elseif ($data->getTransactionStatus() == 103) {
                                echo $this->helper('novalnet_payment')->__('Transaction deactivate');
                            } elseif (in_array($data->getTransactionStatus(), array(
                                        98, 99, 91))) {
                                echo $this->helper('novalnet_payment')->__('TID on hold');
                            } elseif ($data->getTransactionStatus() == 90) {
                                echo $this->helper('novalnet_payment')->__('PayPal Payment Pending');
                            }
                            ?>
                        </strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Transaction-Status') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getTransactionStatus() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('NC No') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getNcNo() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Customer-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getCustomerId() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Amount') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo sprintf('%.2f', $data->getAmount()) . " " . $this->getCurrencyCode() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Payment Name') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $this->getPaymentTitle() ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <!--Novalnet Order Shop Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Shop Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list" width="100%">
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Shop URL') ?></label>
                    </td>
                    <td style="word-break:break-word;">
                        <strong><?php echo $data->getShopUrl() ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="box-right">
    <!--Novalnet Order Additional Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Additional Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Additional Data') ?></label>
                    </td>
                    <td style="word-break:break-word;">
                        <strong><?php echo $data->getAdditionalData() ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>
