<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Mage
 * @package    Mage_Novalnet
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_info = $this->getInfo();
$transactionId = $this->getAdditionalData('NnTid') ? $this->getAdditionalData('NnTid') : $_info->getLastTransId();
$helper = Mage::helper('novalnet_payment');
?>
<?php if ($this->getAdditionalData('NnTestOrder')) echo $this->__('Testorder'); ?>{{pdf_row_separator}}
<strong><?php echo Mage::helper('novalnet_payment')->__('%s', $this->getMethod()->getTitle()) ?></strong>{{pdf_row_separator}}
<?php echo Mage::helper('novalnet_payment')->__('Novalnet Transaction ID: %s', $helper->makeValidNumber($transactionId)) . '<br>'; ?>{{pdf_row_separator}}
<?php if ($this->getAdditionalData('voidTid')) echo $this->__('Transaction deactivated successfully') . '<br><br>' ?>{{pdf_row_separator}}
<?php if ($this->getAdditionalData('refunded_tid')):
        foreach($this->getAdditionalData('refunded_tid') as $key => $value):
            if ($this->getAdditionalData('fullRefund') == true):
                echo $this->__('Refunded Transaction ID: %s', $helper->makeValidNumber($value['reftid'])) . '<br><br>';
            elseif(preg_match("/refund/i", $value['reftid'])):
                echo $this->__('For Tid: %s', $helper->makeValidNumber($value['reqtid'])) . ' ' . $this->__('amount refunded is %s', $value['refamount']) . '<br><br>';
            else:
                echo $this->__('For Tid: %s', $helper->makeValidNumber($value['reqtid'])) . ' ' . $this->__('refund amount %s', $value['refamount']) . ', ' . $this->__('New Tid: %s', $value['reftid']) . ' ' . $this->__('for the balance amount.') . '<br><br>';
            endif;
        endforeach;
      endif;
?>{{pdf_row_separator}}
