<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$_info = $this->getInfo();
$transactionId = $this->getAdditionalData('NnTid') ? $this->getAdditionalData('NnTid') : $_info->getLastTransId();
$helper = Mage::helper('novalnet_payment');
if ($_info):
?>
<?php
if ($this->getAdditionalData('NnTestOrder'))
        echo '<div style="color:white;font-weight:bold;background:red;padding:5px 10px;text-align:center;font-size:15px">!', $this->__('Testorder'), '!</div>'
    ?>
<?php echo $this->htmlEscape($this->getPaymentMethod()) ?><br />
<?php if ($transactionId) echo $this->__('Novalnet Transaction ID: %s', $helper->makeValidNumber($transactionId)) . '<br /><br>' ?>
<?php if ($this->getAdditionalData('voidTid')) echo $this->__('Transaction deactivated successfully') . '<br><br>' ?>
<?php if ($this->getAdditionalData('refunded_tid')):
        foreach($this->getAdditionalData('refunded_tid') as $key => $value):
            if ($this->getAdditionalData('fullRefund') == true):
                echo $this->__('Refunded Transaction ID: %s', $helper->makeValidNumber($value['reftid'])) . '<br><br>';
            else:
                echo $this->__('New Tid: %s', $helper->makeValidNumber($value['reftid'])) . ' ' . $this->__('for the refunded amount %s', $value['refamount']) . '<br><br>';
            endif;
        endforeach;
      endif;
?>
<?php if ($this->getAdditionalData('NnComments')) echo $this->getAdditionalData('NnComments'); ?>
<?php else: ?>
    <?php echo $this->__('Error in getting payment method') ?>
<?php endif; ?>
