<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_info = $this->getInfo();
$transactionId = $this->getAdditionalData('NnTid') ? $this->getAdditionalData('NnTid') : $_info->getLastTransId();
$helper = Mage::helper('novalnet_payment');
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$currentTime = $this->getAdditionalData('voidCreateAt');
$captureTime = $this->getAdditionalData('CaptureCreateAt');
$nextCycleId = $this->getAdditionalData('NnSepaParentTid') ? $this->getAdditionalData('NnSepaParentTid') : $this->getAdditionalData('NnTid');
$nextCycleDate = $helper->getCycleDate($nextCycleId);
?>
<?php if ($this->getAdditionalData('NnTestOrder')) echo $this->__('Testorder'); ?>{{pdf_row_separator}}
<strong><?php echo Mage::helper('novalnet_payment')->__('%s', $this->getMethod()->getTitle()) ?></strong>{{pdf_row_separator}}
<?php echo Mage::helper('novalnet_payment')->__('Novalnet Transaction ID: %s', $helper->makeValidNumber($transactionId)) . '<br>'; ?>{{pdf_row_separator}}
<?php if ($nextCycleDate) echo $this->__('Next Payment Date is: %s', $nextCycleDate) . '<br>' ?>{{pdf_row_separator}}
<?php if ($this->getAdditionalData('captureTid')) echo $this->__('The transaction has been confirmed on %s', $captureTime) . '<br>' ?>{{pdf_row_separator}}
<?php if ($this->getAdditionalData('subsCancelReason')) echo $this->__('Subscription Cancellation: %s', $this->getAdditionalData('subsCancelReason')) . '<br>' ?>{{pdf_row_separator}}
<?php if ($this->getAdditionalData('voidTid')) echo $this->__('The transaction has been canceled on %s', $currentTime) . '<br><br>' ?>{{pdf_row_separator}}
<?php
if ($this->getAdditionalData('refunded_tid')):
    foreach ($this->getAdditionalData('refunded_tid') as $key => $value):
        echo $this->__('The refund has been executed for the TID: %s with the amount of %s', $helper->makeValidNumber($value['reqtid']), $value['refamount']) . '<br><br>';
        ?>
        {{pdf_row_separator}}
        <?php
    endforeach;
endif;
?>{{pdf_row_separator}}
<?php if (!preg_match("/invoice|creditmemo|shipment|callback_novalnet2magento/i", $currentUrl)): ?>
    <?php
    if (strlen($this->getAdditionalData('NnNote'))):
        if (strstr($this->getAdditionalData('NnNote'), 'br')):
            echo nl2br($this->getAdditionalData('NnNote'));
        else:
            $note = explode('|', $this->getAdditionalData('NnNote'));
            echo '<br><b>' . $this->__('Please transfer the invoice amount with the following information to our payment provider Novalnet AG') . '</b></br>';
            foreach ($note as $noteValue):
                list($text, $value) = explode(':', $noteValue);
                echo $this->__($text) . ' : ' . $value
                ?> {{pdf_row_separator}} <?php
            endforeach;
        endif;
    endif;
    ?>{{pdf_row_separator}}
    <?php
    if (strlen($this->getAdditionalData('NnNoteAmount'))):
        list ($text, $value) = explode(':', $this->getAdditionalData('NnNoteAmount'));
        echo $this->__($text) . ' : ' . $value;
    endif;
    ?>{{pdf_row_separator}}
    <?php
    if (strlen($this->getAdditionalData('NnNoteTID'))):
        if (strstr($this->getAdditionalData('NnNoteTID'), 'br')):
            echo nl2br($this->getAdditionalData('NnNoteTID'));
        else:
            $note = explode('|', $this->getAdditionalData('NnNoteTID'));
            echo "<br />";
            foreach ($note as $noteValue):
                list($text, $value) = explode(':', $noteValue);
                if (preg_match("/Order No&/i", $value)):
                    list($referenceTxt, $value) = explode('&', $value);
                    str_replace('&', '', $referenceTxt);
                    echo $this->__($text) . ' : ' . '<b>' . $this->__($referenceTxt) . ' ' . $value . '</b></br>';
                else:
                    if ($text == 'NN_Reference_desc1' || $text == 'NN_Reference_desc2'):
                        echo '<b>' . $this->__($text) . '</b></br>';
                    else:
                        echo $this->__($text) . ' : ' . $value
                        ?> {{pdf_row_separator}} <?php
                    endif;
                endif;
            endforeach;
        endif;
    endif;
    ?>{{pdf_row_separator}}
    <?php
    if (strlen($this->getAdditionalData('NnComments'))):
        echo nl2br($this->getAdditionalData('NnComments')) . '<br>';
    endif;
    ?>{{pdf_row_separator}}
<?php endif; ?>
