<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="switcher">
    <label for="store_switcher"><?php echo $this->__('Current Configuration Scope:') ?></label>
    <select id="store_switcher" class="system-config-store-switcher" onchange="location.href = this.options[this.selectedIndex].getAttribute('url')">
        <?php foreach ($this->getStoreSelectOptions() as $_value => $_option): ?>
            <?php if (isset($_option['is_group'])): ?>
                <?php if ($_option['is_close']): ?>
                    </optgroup>
                <?php else: ?>
                    <optgroup label="<?php echo $_option['label'] ?>" style="<?php echo $_option['style'] ?>">
                    <?php endif; ?>
                    <?php continue ?>
                <?php endif; ?>
                <option value="<?php echo $_value ?>" url="<?php echo $_option['url'] ?>" <?php
                echo $_option['selected'] ? 'selected="selected"' : ''
                ?> style="<?php echo $_option['style'] ?>">
                            <?php echo $_option['label'] ?>
                </option>
            <?php endforeach ?>
    </select>
</div>
