<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$config = $helper->getModel('Service_Abstract');
$billingInfo = $this->getBillingInfo();
?>

<ul class="form-list" id="payment_form_<?php echo $code; ?>" style="display:none;">
    <!-- Direct Debit SEPA payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
            <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" class="nnlogo-href">
                <?php $imgpath = $helper->getPaymentLogoUrl() . "sepa.png"; ?>
                <img class="nnlogo-img" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
            </a>
        <?php endif; ?>
    </div>
    <!-- Direct Debit SEPA payment logo -->
    <div class="nnloader" id='sepa_loading' style="background: url('<?php echo $helper->getPaymentLogoUrl(); ?>novalnet-loading-icon.gif') 50% 50% no-repeat;"></div>
    <!-- Payment description -->
    <li>
        <?php echo $this->__('Your account will be debited upon the order submission'); ?>
    </li>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo(); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == false): ?>
        <li>
            <div class="nn-mode">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged'); ?>
            </div>
        </li>
    <?php endif; ?>
    <!-- Display the payment mode notification -->
    <!-- Direct Debit SEPA local form -->
    <div id="sepa_local_form">
        <li>
            <label style="float:none;" for="<?php echo $code ?>_account_holder"><?php echo $this->__('Account Holder') ?><span class="required">*</span></label><br/>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_account_holder" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" name="<?php echo $code ?>_account_holder" autocomplete="off" value="<?php echo $billingInfo->getFirstname() . ' ' . $billingInfo->getLastname(); ?>" />
            </div>
        </li>
        <li>
            <label style="float:none;" for="<?php echo $code ?>_bank_country"><?php echo $this->__('NN Country') ?><span class="required">*</span></label><br />
            <div class="input-box">
                <?php
                $_countries = Mage::getResourceModel('directory/country_collection')
                        ->loadData()
                        ->toOptionArray(false);
                $specific = explode(",", $this->getMethod()->getConfigData('specificcountry'));
                ?>
                <?php if (count($_countries) > 0): ?>
                    <select id="<?php echo $code ?>_bank_country" onchange="unsetHashRelatedElements()" class="required-entry">
                        <?php foreach ($_countries as $_country): ?>
                            <?php if (in_array($billingInfo->getCountryId(), $_country)): ?>
                                <option selected value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?>
                                </option>
                            <?php else: ?>
                                <?php if (!empty($specific[0])): ?>
                                    <?php foreach ($specific as $val): ?>
                                        <?php if ($val == $_country['value']): ?>
                                            <option value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <option value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?></option>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select><br/>
                <?php endif; ?>
            </div>
        </li>
        <li>
            <label style="float:none;" for="<?php echo $code ?>_account_number"><?php echo $this->__('IBAN or Account number') ?><span class="required">*</span></label><br/>
            <div class="input-box">
                <input type="text" id="<?php echo $code ?>_account_number" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" title="<?php echo $this->__('IBAN or Account number') ?>" class="required-entry input-text" autocomplete="off" value="" />
            </div>
        </li>
        <li>
            <label style="float:none;" for="<?php echo $code ?>_bank_code"><?php echo $this->__('BIC or Bank code') ?><span class="required">*</span></label><br/>
            <div class="input-box">
                <input type="text" id="<?php echo $code ?>_bank_code" title="<?php echo $this->__('BIC or Bank code') ?>" class="input-text" autocomplete="off" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements()" value="" />
            </div>
        </li>
        <li class="fields">
            <div class="input-box">
                <input type="checkbox" id="<?php echo $code ?>_mandate_confirm" title="<?php echo $this->__('confirm') ?>" class="required-entry" onclick="sepaHashProcess(this, '<?php echo $this->__('Your account details are invalid') ?>', '<?php echo $this->__('Basic parameter not valid') ?>')"/>
                <label style="float:none;" ><?php echo $this->__('NN Confirm') ?><span class="required">*</span></label><br/>
            </div>
        </li>
        <!-- DOB for Direct Debit SEPA payment guarantee -->
        <?php if ($helper->getMethodSession($code)->getPaymentGuaranteeFlag()): ?>
            <li>
                <label for="<?php echo $code ?>_dob"><?php echo $this->__('Date Of Birth') ?><span class="required">*</span></label><br/>
                <div class="input-box">
                    <input type="text" autocomplete="off" id="<?php echo $code ?>_dob" name="payment[dob]"
                    title="<?php echo $this->__('DOB') ?>" class="required-entry validate-date" value="<?php echo date('Y-m-d');?>" readonly="readonly"/>
                </div>
            </li>
        <?php endif ?>
        <!-- DOB for Direct Debit SEPA payment guarantee -->
    </div>
    <!-- Direct Debit SEPA local form -->
    <!-- Form hidden elements -->
    <input id="process_vendor_id" type="hidden"  value="<?php echo $config->vendorId; ?>"/>
    <input id="auth_code" type="hidden" value="<?php echo $config->authcode; ?>"/>
    <input id="nnSepa_new_form" name="nnSepa_new_form" type="hidden" value="" />
    <input id="sepaiban" type="hidden" value="">
    <input id="sepabic" type="hidden" value="">
    <input id="result_mandate_unique" type="hidden" value="" name="result_mandate_unique">
    <input id="result_sepa_hash" type="hidden" value="" name="result_sepa_hash">
    <input id="nnsepa_iban_confirmed" type="hidden" value="0" name="nnsepa_iban_confirmed">
    <input id="nn_sepa_merchant_validate_error_message" type="hidden" value="<?php echo $this->__('Basic parameter not valid') . '!'; ?>" />
    <input id="nn_sepa_validate_error_message" type="hidden" value="<?php echo $this->__('Your account details are invalid') . '!'; ?>" />
    <!-- Form hidden elements -->
</ul>
<script type="text/javascript">
    if (document.getElementById("<?php echo $code ?>_dob") != undefined) {
        Calendar.setup({
            inputField: "<?php echo $code ?>_dob",
            ifFormat: '%Y-%m-%d',
            button: 'date_to_trig',
            align: 'Bl',
            singleClick: true
        });
    }
</script>
