<!--div class="box base-mini mini-su-infobox">
    <div class="head">
        <h4><?php echo $this->__('Sofortueberweisung'); ?></h4>
    </div>
    <div class="content">
		<a href="https://www.novalnet.de" title="Informationen zu Novalnet AG"><img src="<?php $this->getSkinUrl() ?>images/sofortueberweisung/logo_sofortueberweisung170.jpg" alt="Sofortüberweisung" title="Sofortüberweisung"></a>
		<p>
			<ul style="list-style-type:disc;">
				<li style="margin-left:15px;"><?php echo $this->helper('sofortueberweisung')->__('Fast shippiung') ?></li>
				<li style="margin-left:15px;"><?php echo $this->helper('sofortueberweisung')->__('Privacy') ?></li>
				<li style="margin-left:15px;"><?php echo $this->helper('sofortueberweisung')->__('No registration') ?></li>
				<li style="margin-left:15px;"><?php echo $this->helper('sofortueberweisung')->__('Save payment') ?></li>
			</ul>
		</p>
    </div>
    <div class="actions">
        <a href="https://www.novalnet.de"><small><?php echo $this->__('More') ?></small></a>
    </div>
</div-->