<?php if( $this->getInfo()->getNnTestorder() ) echo '<div style="color:white;font-weight:bold;background:red;padding:5px 10px;text-align:center;font-size:15px">!',$this->__('Testorder'),'!</div>' ?>
<p><?php  echo $this->getMethod()->getTitle() ?></p>
<?php if($_info = $this->getInfo()):?>
	
	<?php if($this->getInfo()->getSuHolder()): ?>
		<?php echo $this->__('Account holder: %s', $this->getInfo()->getSuHolder())?><br/>
		<?php echo $this->__('Account number: %s', 'xxxx'.substr($this->getInfo()->getSuAccountNumber(),4,strlen($this->getInfo()->getSuAccountNumber())))?><br/>
		<?php echo $this->__('Bank code: %s', $this->getInfo()->getSuBankCode())?><br/>
	<?php endif; ?>
	
	<?php if($this->getInfo()->getLastTransId()): ?>
		<?php echo $this->__('TID: %s', $this->getInfo()->getLastTransId())?><br/>
	<?php endif; ?>
<?php else: ?>

<?php endif; ?>