<!-- Here we can print the custom message for the front end user -->
<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2012 Novalnet AG
 * @version    3.0.1
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
	$code=$this->getMethodCode();
	$baseUrl=Mage::getBaseUrl('skin');
?>
  <fieldset class="form-list">
    <div>
     <A HREF="<?php echo Mage::helper('novalnet')->nn_url();?>" TARGET="_new" style="text-decoration:none;">	
    	<?php $imgpath = "https://www.novalnet.de/images/paypal.gif";  ?>
		<img style="height:32px;" src='<?php echo $imgpath; ?>' alt='<?php echo $this->getMethod()->getConfigData('title'); ?>' title='<?php echo $this->getMethod()->getConfigData('title'); ?>' />
   </A></div>
  <div>
		<ul id="payment_form_<?php echo $code ?>" style="display:none">
			<li>
            <?php echo $this->__('You will be redirected to Novalnet AG website when you place an order.') ?>
			</li>
		</ul>
    </div>
  </fieldset>

