<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$config = $helper->getModel('Service_Abstract');
$billingInfo = $this->getBillingInfo();
$refillParams = $this->getRefillParams();
$maskedAccountInfo = $this->getMethod()->getMaskedAccountInfo();
$oneClickShopping = ($this->getMethod()->getConfigData('sepa_shop_type') == 1 && $maskedAccountInfo) ? 1 : '';
?>

<ul class="form-list" id="payment_form_<?php echo $code; ?>" style="display:none;">
    <!-- Direct Debit SEPA payment logo -->
    <div>
        <?php if ($this->logoAvailableStatus()): ?>
            <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" class="nnlogo-href">
                <?php $imgpath = $helper->getPaymentLogoUrl() . "sepa.png"; ?>
                <img class="nnlogo-img" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
            </a>
        <?php endif; ?>
    </div>
    <!-- Direct Debit SEPA payment logo -->
    <div class="nnloader" id='sepa_loading' style="background: url('<?php echo $helper->getPaymentLogoUrl(); ?>novalnet-loading-icon.gif') 50% 50% no-repeat;"></div>
    <!-- Payment description -->
    <li>
        <?php echo $this->__('Your account will be debited upon the order submission'); ?>
    </li>
    <!-- Payment description -->
    <!-- Information to the end customer -->
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo(); ?>
        </li>
    <?php endif; ?>
    <!-- Information to the end customer -->
    <!-- Display the payment mode notification -->
    <?php if ($this->getPaymentMode() == false): ?>
        <li>
            <div class="nn-mode">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged'); ?>
            </div>
        </li>
    <?php endif; ?>
    <!-- Display the payment mode notification -->
    <!-- Direct Debit SEPA shopping type link -->
    <div id="sepa_oneclick_link" style="cursor:pointer;display:none;">
        <ul>
            <li>
                <span id ='sepa_title_new' onclick='SepaFormChange("new")' style='color:blue'>
                    <u><b><?php echo $this->__('Enter account details'); ?></b></u>
                </span>
                <span id ='sepa_title_given' onclick='SepaFormChange("given")' style='color:blue'>
                    <u><b><?php echo $this->__('Given account details'); ?></b></u>
                </span>
            </li>
        </ul>
    </div>
    <!-- Direct Debit SEPA shopping type link -->
    <!-- Direct Debit SEPA given form -->
    <div id="sepa_oneclick_given">
        <?php if ($oneClickShopping): ?>
            <ul>
                <li>
                    <label><?php echo $this->__('Account Holder') . ': ' . $maskedAccountInfo['account_holder']; ?> </label>
                </li>
                <li>
                    <label><?php echo $this->__('IBAN') . ': ' . $maskedAccountInfo['iban']; ?></label>
                </li>
                <li>
                    <label><?php echo $this->__('BIC') . ': ' . $maskedAccountInfo['bic']; ?></label>
                </li>
                <li class="fields">
                    <div class="input-box">
                        <input type="checkbox" id="<?php echo $code ?>_mandate_confirm_ocs" title="<?php echo $this->__('confirm') ?>"
                        class="required-entry" onclick="oneClickShopConfirm(this)" />
                        <label class="required" style="display:inline;"><?php echo $this->__('NN Confirm') ?></label>
                    </div>
                </li>
            </ul>
        <?php Endif; ?>
    </div>
    <!-- Direct Debit SEPA given form -->
    <!-- Direct Debit SEPA local form -->
    <div id="sepa_local_form">
        <li>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <label for="<?php echo $code ?>_account_holder" class="required"><em>*</em><?php echo $this->__('Account Holder') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_account_holder" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" name="<?php echo $code ?>_account_holder" autocomplete="off" value="<?php echo $billingInfo->getFirstname() . ' ' . $billingInfo->getLastname(); ?>" />
            </div>
        </li>
        <li>
            <label for="<?php echo $code ?>_bank_country" class="required"><em>*</em><?php echo $this->__('NN Country') ?></label>
            <div class="input-box">
                <?php
                $_countries = Mage::getResourceModel('directory/country_collection')
                        ->loadData()
                        ->toOptionArray(false);
                $specific = explode(",", $this->getMethod()->getConfigData('specificcountry'));
                ?>
                <?php if (count($_countries) > 0): ?>
                    <select id="<?php echo $code ?>_bank_country" onchange="unsetHashRelatedElements()" class="required-entry">
                        <?php foreach ($_countries as $_country): ?>
                            <?php if (in_array($billingInfo->getCountryId(), $_country)): ?>
                                <option selected value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?>
                                </option>
                            <?php else: ?>
                                <?php if (!empty($specific[0])): ?>
                                    <?php foreach ($specific as $val): ?>
                                        <?php if ($val == $_country['value']): ?>
                                            <option value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?></option>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <option value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?></option>
                                <?php endif; ?>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </select><br/>
                <?php endif; ?>
            </div>
        </li>
        <li>
            <label for="<?php echo $code ?>_account_number" class="required"><em>*</em><?php echo $this->__('IBAN or Account number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $code ?>_account_number" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" title="<?php echo $this->__('IBAN or Account number') ?>" class="required-entry input-text" autocomplete="off" value="" />
            </div>
        </li>
        <li>
            <label for="<?php echo $code ?>_bank_code" class="required"><em>*</em><?php echo $this->__('BIC or Bank code') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $code ?>_bank_code" title="<?php echo $this->__('BIC or Bank code') ?>" class="input-text" autocomplete="off" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements()" value="" />
            </div>
        </li>
        <li class="fields">
            <div class="input-box">
                <input type="checkbox" id="<?php echo $code ?>_mandate_confirm" title="<?php echo $this->__('confirm') ?>" class="required-entry" onclick="sepaHashProcess(this, '<?php echo $this->__('Your account details are invalid') ?>', '<?php echo $this->__('Basic parameter not valid') ?>')"/>
                <label class="required" style="display:inline;"><?php echo $this->__('NN Confirm') ?></label>
            </div>
        </li>
        <!-- Payment fraud prevention form -->
        <?php if ($helper->getModel('Service_Api_FraudPrevention')->getFraudPreventionStatus($this->getMethod()->getInfoInstance(), $code)): ?>
            <!-- PIN by Callback/Sms -->
            <li>
                <label for="<?php echo $code ?>_callback_tel" class="required"><em>*</em>
                    <?php if ($this->getMethod()->getConfigData('callback') == 2): ?>
                        <?php echo $this->__('Mobile phone number'); ?>
                    <?php else: ?>
                        <?php echo $this->__('NN Mobile Number'); ?>
                    <?php endif; ?>
                </label>
                <div class="input-box">
                    <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text validate-number" value="<?php echo $billingInfo->getTelephone(); ?>"/>
                </div>
            </li>
            <li>
                <div class="nncallback-note">
                    <?php echo $this->__('Note for pin by sms and callback') ?>
                </div>
                <label for="<?php echo $code ?>_callback_pin" class="required"><em>*</em><?php echo $this->__('PIN') ?></label>
                <div class="input-box">
                    <input onkeydown="document.getElementById('<?php echo $code ?>_callback_new_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                    <input id="<?php echo $code ?>_callback_new_pin" type="checkbox" name="payment[callback_new_pin]" value="1">
                    <label style="float:none;" for="<?php echo $code ?>_callback_new_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                </div>
            </li>
            <!-- PIN by Callback/Sms -->
        <?php endif; ?>
        <!-- Payment fraud prevention form -->
    </div>
    <!-- Direct Debit SEPA local form -->
    <!-- DOB for Direct Debit SEPA payment guarantee -->
    <?php if ($helper->getMethodSession($code)->getPaymentGuaranteeFlag()): ?>
    <div id="sepa_guarantee">
        <li>
            <label for="<?php echo $code ?>_dob" class="required"><em>*</em><?php echo $this->__('Date Of Birth') ?></label>
            <div class="input-box">
                <input type="text" autocomplete="off" id="<?php echo $code ?>_dob" name="payment[dob]"
                title="<?php echo $this->__('DOB') ?>" class="required-entry validate-date" value="<?php echo date('Y-m-d');?>" readonly="readonly"/>
            </div>
        </li>
    </div>
    <?php endif ?>
    <!-- DOB for Direct Debit SEPA payment guarantee -->
    <!-- Form hidden elements -->
    <input id="process_vendor_id" type="hidden"  value="<?php echo $config->vendorId; ?>"/>
    <input id="auth_code" type="hidden" value="<?php echo $config->authcode; ?>"/>
    <input id="nnSepa_oneclick_shopping" name="nnSepa_oneclick_shopping" type="hidden" value="<?php echo $oneClickShopping; ?>" />
    <input id="nnSepa_new_form" name="nnSepa_new_form" type="hidden" value="<?php echo $refillParams['sepaNewForm'] ?>" />
    <input id="sepaiban" type="hidden" value="">
    <input id="sepabic" type="hidden" value="">
    <input id="result_mandate_unique" type="hidden" value="" name="result_mandate_unique">
    <input id="nnsepa_iban_confirmed" type="hidden" value="0" name="nnsepa_iban_confirmed">
    <input id="result_sepa_hash" type="hidden" value="<?php echo $refillParams['sepaHash']; ?>" name="result_sepa_hash">
    <input id="nn_sepa_merchant_validate_error_message" type="hidden" value="<?php echo $this->__('Basic parameter not valid') . '!'; ?>" />
    <input id="nn_sepa_validate_error_message" type="hidden" value="<?php echo $this->__('Your account details are invalid') . '!'; ?>" />
    <!-- Form hidden elements -->
</ul>
<script type="text/javascript">
    if (document.getElementById("<?php echo $code ?>_dob") != undefined) {
        Calendar.setup({
            inputField: "<?php echo $code ?>_dob",
            ifFormat: '%Y-%m-%d',
            button: 'date_to_trig',
            align: 'Bl',
            singleClick: true
        });
    }
</script>
