<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_info = $this->getInfo();
$transactionId = $this->getAdditionalData('NnTid') ? $this->getAdditionalData('NnTid') : $_info->getLastTransId();
$helper = Mage::helper('novalnet_payment');
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
?>
<?php if ($_info): ?>
    <?php
    if ($this->getAdditionalData('NnTestOrder'))
            echo '<div style="color:white;font-weight:bold;background:red;padding:5px 10px;text-align:center;font-size:15px">!', $this->__('Testorder'), '!</div>'
    ?>
    <?php echo $this->htmlEscape($this->getMethod()->getTitle()) ?><br />
    <?php if ($transactionId) echo $this->__('Novalnet Transaction ID: %s', $helper->makeValidNumber($transactionId)) . '<br />' ?>
    <?php if ($this->getAdditionalData('voidTid')) echo '<br>' . $this->__('Transaction deactivated successfully') . '<br>' ?>
    <?php if ($this->getAdditionalData('refunded_tid')):
            foreach($this->getAdditionalData('refunded_tid') as $key => $value):
                if ($this->getAdditionalData('fullRefund') == true):
                    echo '<br>' . $this->__('Refunded Transaction ID: %s', $helper->makeValidNumber($value['reqtid'])) . '<br>';
                else:
                    echo '<br>' . $this->__('For Tid: %s', $helper->makeValidNumber($value['reqtid'])) . ' ' . $this->__('amount refunded is %s', $value['refamount']) . '<br>';
                endif;
            endforeach;
          endif;
    ?>
    <?php if (!preg_match("/creditmemo|callback_novalnet2magento/i", $currentUrl)): ?>
    <?php
    if (strlen($this->getAdditionalData('NnNote'))):
        if (strstr($this->getAdditionalData('NnNote'), 'br')):
            echo nl2br($this->getAdditionalData('NnNote'));
        else:
            $note = explode('|',$this->getAdditionalData('NnNote'));
            echo '<br><b>' . $this->__('Please transfer the invoice amount with the following information to our payment provider Novalnet AG') . '</b></br>';
            foreach($note as $noteValue):
                list($text, $value) = explode(':', $noteValue);
                echo $this->__($text) . ' : '. $value . '</br>';
            endforeach;
        endif;
    endif;
    ?>
    <?php
    if (strlen($this->getAdditionalData('NnNoteAmount'))):
        list ($text, $value) = explode(':',$this->getAdditionalData('NnNoteAmount'));
        echo $this->__($text) . ' : '. $value;
    endif;
    ?>
    <?php
    if (strlen($this->getAdditionalData('NnNoteTID'))):
        if (strstr($this->getAdditionalData('NnNoteTID'), 'br')):
            echo nl2br($this->getAdditionalData('NnNoteTID'));
        else:
            $note = explode('|',$this->getAdditionalData('NnNoteTID'));
            echo "<br />";
            foreach($note as $noteValue):
                list($text, $value) = explode(':', $noteValue);
                if ($text == 'NN_Reference3'):
                    list($referenceTxt, $value) = explode('&', $value);
                    str_replace('&', '', $referenceTxt);
                    echo $this->__($text) . ' : '. '<b>'.$this->__($referenceTxt) . ' '. $value . '</b></br>';
                else:
                    echo $this->__($text) . ' : '. $value . '</br>';
                endif;
            endforeach;
        endif;
     endif;
    ?>
    <?php
    if (strlen($this->getAdditionalData('NnComments'))):
        echo nl2br($this->getAdditionalData('NnComments')) . '<br>';
     endif;
    ?>
    <?php endif; ?>
<?php else: ?>
    <?php echo $this->__('Error in getting payment method') ?>
<?php endif; ?>

