<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->getHeaderText() ?></h3></td>
        </tr>
    </table>
</div>

<?php echo $this->getViewHtml() ?>

<div class="content-header" id="novalnet_wizard_form_buttons">
    <table cellspacing="0">
        <tr>
            <td class="form-buttons">
                <?php echo $this->getButtonsHtml() ?>
            </td>
        </tr>
    </table>
</div>
