<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2012 Novalnet AG
 * @version    3.0.1
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php
	$code    = $this->getMethodCode();
	$baseUrl = Mage::getBaseUrl('skin')
?>
<?php if ($this->checkCustomerAccess()):?>
  <fieldset class="form-list">
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <li>
            <div class="input-box">
				<?php echo $this->__($this->htmlEscape('The Bank details will be emailed to you soon after the completion of checkout process'))?><br />
            </div>
        </li>
    </ul>
  </fieldset>
<?php else: ?>
	<script type="text/javascript">
		function hideMe(payment_code){
			t = 'p_method_' + payment_code.toString();
			document.getElementById(t).style.visibility = 'hidden';
			aTags = document.getElementsByTagName("label");
			if (aTags && aTags.length) {
				for (i=0; i<aTags.length; i++){
					if (aTags[i].htmlFor == t){
						aTags[i].style.visibility = 'hidden';
						i = aTags.length;
					}
				}
			}
		}
		<?php echo "hideMe('$code');"; ?>
	</script>  
<?php endif; ?>
