<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2012 Novalnet AG
 * @version    3.0.1
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php 
	$code=$this->getMethodCode();
	$baseUrl=Mage::getBaseUrl('skin');
?>
<?php if ($this->checkCustomerAccess()):?>
  <fieldset class="form-list">
    <?php if($code!='novalnetCcpci'): ?>
       <div style="width:100px;">
		<?php  $imgpath = "images/novalnet/ELV_Logo.png";  ?>
		<img style="height:20px;" src='<?php echo Mage::getDesign()->getSkinUrl($imgpath) ?>' alt='ELV Logo'/>
      <?php else:?>
        <div style="width:130px;">
       <?php foreach($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
			<?php $imgpath = "images/novalnet/". $_typeCode ."_Logo.png";  ?>
			<img style="height:20px;" src='<?php echo Mage::getDesign()->getSkinUrl($imgpath) ?>' alt='<?php echo $_typeName; ?> Logo'/>
		<?php endforeach; ?>
    <?php endif; ?>
	</div>
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
		<li>
            <?php echo $this->__('You will be redirected to Novalnet AG website when you place an order.') ?>
        </li>
    </ul>
  </fieldset>
<?php else:?>
	<script type="text/javascript">
		function hideMe(payment_code){
			t = 'p_method_' + payment_code.toString();
			document.getElementById(t).style.visibility = 'hidden';
			aTags = document.getElementsByTagName("label");
			if (aTags && aTags.length) {
				for (i=0; i<aTags.length; i++){
					if (aTags[i].htmlFor == t){
						aTags[i].style.visibility = 'hidden';
						i = aTags.length;
					}
				}
			}
		}
		<?php echo "hideMe('$code');"; ?>
	</script>  
<?php endif; ?>
