<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Novalnet AG
 * @version    1.0.0
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php
$customer_id = $_SESSION['customer_base']['id'];
$accountData = $this->getAccountData($customer_id);
$nn_account_holder = $nn_account_number = $nn_bank_sorting_code = $nn_elv_country = '';
if ($accountData){
	list($nn_account_holder, $nn_account_number, $nn_bank_sorting_code, $nn_elv_country) = array_values($accountData);
	$nn_account_number = substr($nn_account_number, 0, -4);
	$nn_bank_sorting_code = substr($nn_bank_sorting_code, 0, -3);
}
$user_group_id = $this->getUserGroupId($customer_id);
$user_group_name = $this->getUserGroupExcluded();
if (!$user_group_name){$allowed = true;}
else{$allowed = $this->checkUserGroupAccess($user_group_id, $user_group_name);}
?>
<?php $_code=$this->getMethodCode() ?>
<?php $baseUrl=Mage::getBaseUrl('skin') ?>
<?php if ($allowed) {?>
<fieldset class="form-list">
	<div style="position: relative; left: 14em; top: -2.5em">
		<img src='<?php echo $baseUrl?>frontend/default/default/images/novalnet/ELV_Logo.png' alt='ELV Logo'/>
	</div>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_account_holder"><?php echo $this->__('Account Holder') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $_code ?>_account_holder" name="payment[account_holder]" title="<?php echo $this->__('Account Holder') ?>" class="required-entry input-text" value="<?=$nn_account_holder?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $_code ?>_account_number" name="payment[account_number]" title="<?php echo $this->__('Account Number') ?>" class="required-entry input-text" value="<?=$nn_account_number?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_bank_sorting_code"><?php echo $this->__('Bank Sorting Code') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $_code ?>_bank_sorting_code" name="payment[bank_sorting_code]" title="<?php echo $this->__('Bank Sorting Code') ?>" class="required-entry input-text" value="<?=$nn_bank_sorting_code?>" />
            </div>
        </li>
		<?php if($this->acdc_check()): ?>
		<li>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_checkbox" name="payment[checkbox]" title="<?php echo $this->__('Checkbox') ?>" class="required-entry" />
                <label for="<?php echo $_code ?>_checkbox"><?php echo $this->__('The') ?> <b><a href='javascript:show_acdc_info()' ONMOUSEOVER='show_acdc_info()'><?php echo $this->__('ACDC-Check') ?></a></b> <?php echo $this->__('accepted') ?> <span class="required">*</span></label><br/>
            </div>
        </li>
		<?php endif ?>
		<?php if($this->show_comment()): ?>
		<li>
            <div class="input-box">
                <?php echo $this->show_comment()?>
            </div>
        </li>
		<?php endif ?>
    </ul>
	<SCRIPT>
		var showbaby;
		function show_acdc_info(){
			var url=parent.location.href;
			url='<?php echo $baseUrl?>frontend/default/default/images/novalnet/acdc_info.png';w='550';h='300';x=screen.availWidth/2-w/2;y=screen.availHeight/2-h/2;
			showbaby=window.open(url,'showbaby','toolbar=0,location=0,directories=0,status=0,menubar=0,resizable=1,width='+w+',height='+h+',left='+x+',top='+y+',screenX='+x+',screenY='+y);
			showbaby.focus();
		}
			function hide_acdc_info(){showbaby.close();}
	</SCRIPT>
</fieldset><?php }?>
<script type="text/javascript">
	function hideMe(payment_code){
		t = 'p_method_' + payment_code.toString();
		document.getElementById(t).style.visibility = 'hidden';
		aTags = document.getElementsByTagName("label");
		for (i=0; i<aTags.length; i++){
			if (aTags[i].htmlFor == t){
				aTags[i].style.visibility = 'hidden';
				i = aTags.length;
			}
		}
	}
	<?php if (!$allowed){echo"hideMe('$_code')"; }?>
</script>
