<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodul of Novalnet AG
 * http://www.novalnet.de 
 * If you have found this script usefull a small        
 * recommendation as well as a comment on merchant form 
 * would be greatly appreciated.
 * 
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Novalnet AG
 * @version    1.0.0
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_code=$this->getMethodCode() ?>
<?php $baseUrl=Mage::getBaseUrl('skin') ?>
<?php
$_code=$this->getMethodCode();
$customer_id = '';
if ($_SESSION and $_SESSION['customer_base'] and $_SESSION['customer_base']['id'])
{
    $customer_id = $_SESSION['customer_base']['id'];
}
$user_group_id = $this->getUserGroupId($customer_id);
$user_group_name = $this->getUserGroupExcluded();
if (!$user_group_name){$allowed = true;}
else{$allowed = $this->checkUserGroupAccess($user_group_id, $user_group_name);}
?>

<?php if ($allowed) {?>
  <fieldset class="form-list">
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <div class="input-box">
				<?php echo $this->__($this->htmlEscape('The Bank details will be emailed to you soon after the completion of checkout process'))?><br />
            </div>
        </li>
    </ul>
  </fieldset>

<?php }?>
<script type="text/javascript">
	function hideMe(payment_code){
		t = 'p_method_' + payment_code.toString();
		document.getElementById(t).style.visibility = 'hidden';
		aTags = document.getElementsByTagName("label");
		for (i=0; i<aTags.length; i++){
			if (aTags[i].htmlFor == t){
				aTags[i].style.visibility = 'hidden';
				i = aTags.length;
			}
		}
	}
	<?php if (!$allowed){echo"hideMe('$_code')"; }?>
</script>