<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$url = $this->getNovalnetAdminUrl();
?>
<div style="background-color: #0080c9;color: #fff;font-family: calibri;font-size: 15px;font-weight: bold;padding: 5px;text-align: center;"><?php echo $this->__('Login here with Novalnet merchant credentials. For the activation of new payment methods please contact'); ?>&nbsp;<a href= "mailto:support@novalnet.de" style="color:white">support@novalnet.de</a></div>
<div style="width:100%;">
    <iframe src="<?php echo $url ?>" width="100%" frameborder="0" border="0"
            style="min-height:900px; height: 100%; overflow: hidden;">
    </iframe>
</div>
