<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
?>
<fieldset class="form-list" id="fieldset_<?php echo $code ?>"> 
    <!--{{{ Payment Logo -->
        <div>
			<a href="<?php echo $helper->getNovalnetUrl() ?>" target="_new" style="text-decoration:none;">           
                <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . "/img/creditcard_small.jpg" ?>
                <img style="height:20px;" src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->_getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
			</a>
		</div>
    <!--}}} Payment Logo -->
    <!--{{{ Novalnet Cc Form -->
    <div id="payment_form_<?php echo $code ?>" style="display:none;">
        <?php if (!$this->getMethod()->validateNovalnetCcParams()): ?>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Basic parameter not valid') . '!' ?>
            </div>
        <?php else: ?>
            <div id="loading">
                <img src="<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>/img/novalnet-loading-icon.gif" alt="Loading" />
            </div>
            <iframe frameborder="0" name="ifm_payment_form_<?php echo $code ?>" id="ifm_payment_form_<?php echo $code ?>" 
                    style="width: 603px; height: 320px; border: none; display: block; margin-top: 5px;" onload="document.getElementById('loading').style.display = 'none'" src="<?php echo $helper->getUrl('novalnet_payment/NovalnetCc') ?>" >
            </iframe>
            <ul>
	 <!--{{{ CallbackType-->
        <?php if ($this->isCallbackTypeCall()): ?>
            <!--{{{ PIN by Callback-->
            <?php if ($this->getCallbackConfigData() != 3): ?>
                <li>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_tel">
                            <?php if ($this->getCallbackConfigData() == 2): ?>
                                <?php echo $this->__('Mobile phone number'); ?>
                            <?php else: ?>
                                <?php echo $this->__('Ihre Telefon- / Mobil- Nummer'); ?>
                            <?php endif; ?>
                            <span class="required">*</span></label><br/>
                        <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text" />
                    </div>
                </li>
                <li>
                    <div style="font-weight:bold;color:gray;border:1px solid #BFBFBF;font-size:11px; background:#FEFFBF; padding:10px; margin-top:10px;width:400px;">
                        <?php echo $this->__('Hinweis: Nach einem Klick auf "Fortsetzen" erhalten Sie in Kürze eine PIN per Telefon-/Handyrückruf oder SMS.') ?>
                    </div>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_pin"><?php echo $this->__('PIN') ?><span class="required">*</span></label><br/>
                        <input onchange="document.getElementById('new_callback_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                        <input id="new_callback_pin" type="checkbox" name="payment[new_callback_pin]" value="1">
                        <label style="float:none;" for="new_callback_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                    </div>
                </li>
                <!--}}} PIN by Callback-->
                <!--{{{ Reply by Email-->
            <?php elseif ($this->getCallbackConfigData() == 3): ?>
                <li>
                    <div style="font-weight:bold;color:gray;border:1px solid #BFBFBF;font-size:11px; background:#FEFFBF; padding:10px; margin-top:10px;width:400px;">
                        <?php echo $this->__('Hinweis: Nach einem Klick auf "Fortsetzen" erhalten Sie in Kürze ein EMAIL, das Sie sofort ohne änderung des Mailtexts beantworten müssen.') ?>
                    </div>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_email"><?php echo $this->__('Email Address') ?><span class="required">*</span></label><br/>
                        <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_email" name="payment[callback_email]" title="<?php echo $this->__('Callback Email') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
            <?php endif ?>
            <!--}}} Reply by Email-->
        <?php endif ?>
        <!--}}} CallbackType-->
    </ul>
        <?php endif; ?>
    </div>

    <input type="hidden" id="original_vendor_id" value="<?php echo trim($this->getMethod()->_getConfigData('merchant_id', true)) ?>" />
    <input type="hidden" id="original_vendor_authcode" value="<?php echo trim($this->getMethod()->_getConfigData('auth_code', true)) ?>" />

    <input type="hidden" name="novalnet_cc_owner" id="novalnet_cc_owner" value="" />
    <input type="hidden" name="novalnet_cc_type" id="novalnet_cc_type" value="" />
    <input type="hidden" name="novalnet_cc_exp_month" id="novalnet_cc_exp_month" value="" />
    <input type="hidden" name="novalnet_cc_exp_year" id="novalnet_cc_exp_year" value="" />
    <input type="hidden" name="novalnet_cc_cid" id="novalnet_cc_cid" value="" />
    <input type="hidden" name="novalnet_cc_pan_hash" id="novalnet_cc_pan_hash" value="" />
    <input type="hidden" name="novalnet_cc_unique_id" id="novalnet_cc_unique_id" value="" />

</fieldset>
