<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
?>
<fieldset class="form-list">
    <!--{{{ Payment Logo -->
    <div>
        <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" style="text-decoration:none;">
            <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . "/img/" . $_typeCode . "_Logo.png"; ?>
                <img style="height:20px;" src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
            <?php endforeach; ?>
        </a>
    </div>
    <!--}}} Payment Logo -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <li>
            <?php echo $helper->__('The amount will be booked immediately from your credit card.') ?>
        </li>
        <?php if ($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if ($this->getLiveMode() == 0): ?>
            <li>
                <div style="font-weight:bold;color:red;font-size:12px;">
                    <?php echo $helper->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
                </div>
            </li>
        <?php endif ?>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                <select id="<?php echo $code ?>_cc_type" name="payment[nn_cc_type]" class="required-entry validate-cc-type-select">
                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"><?php echo $_typeName ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_cc_owner"><?php echo $this->__('Credit card holder') ?> <span class="required">*</span></label><br/>
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_cc_owner" name="payment[nn_cc_owner]" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_cc_number"><?php echo $this->__('Card number') ?> <span class="required">*</span></label><br/>
                <input type="text" id="<?php echo $code ?>_cc_number" name="payment[nn_cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number validate-cc-type" autocomplete="off" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label style="float:none;" for="<?php echo $code ?>_expiration"><?php echo $this->__('Cc Expiration Date') ?> <span class="required">*</span></label><br />
                <div class="v-fix">
                    <select id="<?php echo $code ?>_expiration" style="width:140px;" name="payment[nn_cc_exp_month]" class="required-entry">
                        <option value=""><?php echo $this->__('Month'); ?></option>
                        <?php foreach ($this->getCcMonths() as $k => $v): ?>
                            <option value="<?php echo $k ?>"><?php echo $v ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="v-fix" style="padding-left:5px;">
                    <select id="<?php echo $code ?>_expiration_yr" style="width:103px;" name="payment[nn_cc_exp_year]" class="required-entry">
                        <option value=""><?php echo $this->__('Year'); ?></option>
                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                            <option value="<?php echo $k ?>"><?php echo $v ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </li>
        <?php if ($this->hasVerification()): ?>
            <li>
                <div class="input-box">
                    <label style="float:none;" for="<?php echo $code ?>_cc_cid"><?php echo $this->__('Cc Card Verification Number') ?> <span class="required">*</span></label><br />
                    <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $code ?>_cc_cid" name="payment[nn_cc_cid]" style="width:3em;" autocomplete="off" maxlength="4" /></div>
                    &nbsp;
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </div>
            </li>
        <?php endif; ?>
    </ul>
</fieldset>
