<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$billingaddress = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
$telephoneNumber = ($this->getCallbackConfigData() == 1 && $billingaddress->getTelephone())
		   ? $billingaddress->getTelephone() : '' ;
?>
<fieldset class="form-list">
    <!-- PAYMENT LOGO -->
    <div>
        <a href="<?php echo $helper->getNovalnetUrl() ?>" target="_new" style="text-decoration:none;">
            <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . "invoice.png"; ?>
            <img src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
        </a>
    </div>
    <!-- PAYMENT LOGO -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <!--{{{ PAYMENT DESCRIPTION  -->
        <li>
            <?php echo $this->__('Invoice/Prepayment payment description') ?>
        </li>
        <?php if ($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if ($this->getMethod()->_getConfigData('live_mode', true) == 0): ?>
            <li>
                <div style="font-weight:bold;color:red;font-size:12px;">
                    <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
                </div>
            </li>
        <?php endif ?>
        <!--}}} PAYMENT DESCRIPTION  -->
        <!--{{{ CallbackType-->
        <?php if ($this->isCallbackTypeCall()): ?>
            <!--{{{ PIN by Callback-->
            <?php if ($this->getCallbackConfigData() != 3): ?>
                <li>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_tel">
                            <?php
                            if ($this->getCallbackConfigData() == 2):
                                ?>
                                <?php echo $this->__('Mobile phone number'); ?>
                            <?php else: ?>
                                <?php echo $this->__('NN Mobile Number'); ?>
                            <?php endif; ?>
                            <span class="required"></span></label><br/>
                        <input type="text" value="<?php echo $telephoneNumber; ?>" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text validate-number" />
                    </div>
                </li>
                <li>
                    <div style="font-weight:bold;color:gray;border:1px solid #BFBFBF;font-size:11px; background:#FEFFBF; padding:10px; margin-top:10px;width:400px;">
                        <?php echo $this->__('Note for pin by sms and callback') ?>
                    </div>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_pin"><?php echo $this->__('PIN') ?><span class="required"></span></label><br/>
                        <input onkeydown="document.getElementById('<?php echo $code ?>_new_callback_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                        <input id="<?php echo $code ?>_new_callback_pin" type="checkbox" name="payment[new_callback_pin]" value="1">
                        <label style="float:none;" for="<?php echo $code ?>_new_callback_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                    </div>
                </li>
                <!--}}} PIN by Callback-->
                <!--{{{ Reply by Email-->
            <?php elseif ($this->getCallbackConfigData() == 3): ?>
                <li>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_email"><?php echo $this->__('E-mail Address') ?><span class="required"></span></label><br/>
                        <input type="text" value="<?php echo $billingaddress->getEmail(); ?>" id="<?php echo $code ?>_callback_email" name="payment[callback_email]" title="<?php echo $this->__('Callback Email') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
            <?php endif ?>
            <!--}}} Reply by Email-->
        <?php endif ?>
        <!--}}} CallbackType-->
    </ul>
</fieldset>
