<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
include(MAGENTO_ROOT.'/novalnet_css_link.php');

$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');

?>
<fieldset class="form-list" id="fieldset_<?php echo $code ?>">
    <!--{{{ Payment Logo -->
        <div>
			<a HREF="<?php echo $helper->getNovalnetUrl();?>" TARGET="_new" style="text-decoration:none;">
				<?php $image = "sepa_logo.jpg";
					  $imgpath = $helper->getNovalnetPaymentFormLogoUrl().$image; ?>
				<img style="height:20px;" src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
			</a>
		</div>
    <!--}}} Payment Logo -->
    <!--{{{ Novalnet SEPA Form -->
    <div id="payment_form_<?php echo $code ?>" style="display:none;">
        <?php if (!$this->getMethod()->validateNovalnetIframeParams()): ?>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Basic parameter not valid') . '!' ?>
            </div>
        <?php else: ?>
            <div id="nn_loading">
                <img src="<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>novalnet-loading-icon.gif" alt="Loading" />
            </div>
            <iframe frameborder="0" scrolling="no" name="ifm_payment_form_<?php echo $code ?>" id="ifm_payment_form_<?php echo $code ?>"
                    style="width: 603px; height: 480px; border: none; display: block; margin-top: 5px;" onload="document.getElementById('nn_loading').style.display = 'none'" src="<?php echo $helper->getUrl('novalnet_payment/NovalnetSepa') ?>" >
            </iframe>
        <?php endif; ?>
    </div>
    <input type="hidden" id="original_sepa_customstyle_css" value="<?php echo NOVALNET_SEPA_CUSTOM_CSS; ?>" />
	<input type="hidden" id="original_sepa_customstyle_cssval" value="<?php echo NOVALNET_SEPA_CUSTOM_CSS_STYLE; ?>" />
	<input type="hidden" name="novalnet_sepa_owner" id="novalnet_sepa_owner" value="" />
    <input type="hidden" name="novalnet_sepa_pan_hash" id="novalnet_sepa_pan_hash" value="" />
    <input type="hidden" name="novalnet_sepa_unique_id" id="novalnet_sepa_unique_id" value="" />
    <input type="hidden" name="novalnet_sepa_mandate_ref" id="novalnet_sepa_mandate_ref" value="" />
    <input type="hidden" name="novalnet_sepa_mandate_date" id="novalnet_sepa_mandate_date" value="" />
    <input type="hidden" name="novalnet_sepa_iban_confirmed" id="novalnet_sepa_iban_confirmed" value="" />
    <input type="hidden" name="novalnet_sepa_field_validator" id="novalnet_sepa_field_validator" value="" />
    <!--}}} Novalnet SEPA Form -->
</fieldset>
