<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$assignDatahelper = Mage::helper('novalnet_payment/AssignData');
$sepaRefill = $this->getMethod()->getNovalnetConfig('auto_refill', true);
$sepaPaymentRefill = $this->getMethod()->getConfigData('sepa_payment_refill');
$refillValues = $assignDatahelper->getCheckout()->getRefilldatavalues();
$refillMethod = ($sepaRefill && $refillValues && $code == $refillValues->getMethod());
// get quote billing address
$checkoutSession = Mage::getSingleton('checkout/session');
$billingaddress = $checkoutSession->getQuote()->getBillingAddress();
$telephoneNumber = ($this->getCallbackConfigData() == 1 && $billingaddress->getTelephone())
           ? $billingaddress->getTelephone() : '' ;
$street = $billingaddress->getStreet();
$customerlogin = Mage::getSingleton('customer/session')->isLoggedIn();
$panhash = '';

if ($sepaPaymentRefill && $customerlogin) {
    $panhash = Mage::getModel('novalnet_payment/separefill')->getSepaPanHash($helper);
} else if ($sepaRefill) {
    $panhash = $assignDatahelper->getCheckout()->getSepaHash();
}

$panhash = (($sepaPaymentRefill || $sepaRefill) && $panhash) ? $panhash : '';
$vendorId = $checkoutSession->getNnVendor() ? $checkoutSession->getNnVendor() : trim($this->getMethod()->getNovalnetConfig('merchant_id', true));
$authCode = $checkoutSession->getNnAuthcode() ? $checkoutSession->getNnAuthcode() : trim($this->getMethod()->getNovalnetConfig('auth_code', true));
?>
<ul class="form-list" id="payment_form_<?php echo $code ?>" style="display:none;">
    <!--{{{ Payment Logo -->
    <div>
        <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" style="text-decoration:none;">
            <?php
            $image = "sepa.png";
            $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . $image;
            ?>
            <img src="<?php echo $imgpath; ?>" alt="<?php echo $this->getMethod()->getConfigData('title'); ?>" title="<?php echo $this->getMethod()->getConfigData('title'); ?>" />
        </a>
    </div>
    <!--}}} Payment Logo -->
    <!--{{{ Novalnet SEPA Form -->
    <div class="nnsepaloader" id='sepa_loading' style='display:none;'></div>
    <li>
        <?php echo $this->__('Your account will be debited upon the order submission'); ?>
    </li>
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo() ?>
        </li>
    <?php endif ?>
    <?php if (Mage::helper('novalnet_payment')->getModel('novalnetSepa')->getNovalnetConfig('live_mode', true) == 0): ?>
        <li>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
            </div>
        </li>
    <?php endif ?>

    <li>
        <label for="<?php echo $code ?>_account_holder" class="required"><em>*</em><?php echo $this->__('Account Holder') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_account_holder" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" name="payment[account_holder]" autocomplete="off" value="<?php echo $billingaddress->getFirstname() . ' ' . $billingaddress->getLastname(); ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $code ?>_bank_country" class="required"><em>*</em><?php echo $this->__('NN Country') ?></label>
        <div class="input-box">
            <?php
            $_countries = Mage::getResourceModel('directory/country_collection')
                    ->loadData()
                    ->toOptionArray(false)
            ?>
            <?php if (count($_countries) > 0): ?>
                <select id="<?php echo $code ?>_bank_country" onchange="unsetHashRelatedElements()" class="required-entry">
                    <?php
                    foreach ($_countries as $_country):
                        if (in_array($billingaddress->getCountryId(), $_country)) {
                            ?>
                            <option selected value="<?php echo $_country['value'] ?>"><?php echo $_country['label'] ?>
                            </option>
                        <?php } else { ?>
                            <option value="<?php echo $_country['value'] ?>">
                                <?php echo $_country['label'] ?>
                            </option>
                        <?php } ?>
                    <?php endforeach; ?>
                </select><br/>
            <?php endif; ?>
        </div>
    </li>
    <li>
        <label for="<?php echo $code ?>_account_number" class="required"><em>*</em><?php echo $this->__('IBAN or Account number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $code ?>_account_number" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements();" title="<?php echo $this->__('IBAN or Account number') ?>" class="required-entry input-text" autocomplete="off" value="" />
        </div>
    </li>

    <li>
        <label for="<?php echo $code ?>_bank_code" class="required"><em>*</em><?php echo $this->__('BIC or Bank code') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $code ?>_bank_code" title="<?php echo $this->__('BIC or Bank code') ?>" class="input-text" autocomplete="off" onkeypress="return ibanbicValidate(event)" onchange="unsetHashRelatedElements()" value="" />
        </div>
    </li>

    <li>
        <div class="input-box">
            <input type="checkbox" id="<?php echo $code ?>_mandate_confirm" title="<?php echo $this->__('confirm') ?>" class="required-entry" onclick="generate_sepa_iban_bic(this, '<?php echo $this->__('Your account details are invalid') ?>', '<?php echo $this->__('Basic parameter not valid') ?>')"/>
            <label class="required" style="float:none;"><?php echo $this->__('NN Confirm') ?></label>
        </div>
    </li>
    <!--{{{ CallbackType-->
    <?php if ($this->isCallbackTypeCall()): ?>
        <!--{{{ PIN by Callback-->
        <?php if ($this->getCallbackConfigData() != 3): ?>
            <li>
                <label for="<?php echo $code ?>_callback_tel" class="required"><em>*</em>
                    <?php if ($this->getCallbackConfigData() == 2): ?>
                        <?php echo $this->__('Mobile phone number'); ?>
                    <?php else: ?>
                        <?php echo $this->__('NN Mobile Number'); ?>
                    <?php endif; ?>
                </label>
                <div class="input-box">
                    <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text validate-number" value="<?php echo $telephoneNumber; ?>"/>
                </div>
            </li>
            <li>
                <div class="nncallbacknote">
                    <?php echo $this->__('Note for pin by sms and callback') ?>
                </div>
                <label for="<?php echo $code ?>_callback_pin" class="required"><em>*</em><?php echo $this->__('PIN') ?></label>
                <div class="input-box">
                    <input onkeydown="document.getElementById('<?php echo $code ?>_new_callback_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                    <input id="<?php echo $code ?>_new_callback_pin" type="checkbox" name="payment[new_callback_pin]" value="1">
                    <label style="float:none;" for="<?php echo $code ?>_new_callback_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                </div>
            </li>
            <!--}}} PIN by Callback-->
            <!--{{{ Reply by Email-->
            <?php elseif ($this->getCallbackConfigData() == 3): ?>
            <li>
                <label for="<?php echo $code ?>_callback_email" class="required"><em>*</em><?php echo $this->__('E-mail Address') ?></label>
                <div class="input-box">
                    <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_email" name="payment[callback_email]" title="<?php echo $this->__('Callback Email') ?>" class="input-text validate-email required-entry" value="<?php echo $billingaddress->getEmail(); ?>"/>
                </div>
            </li>
        <?php endif ?>
        <!--}}} Reply by Email-->
    <?php endif ?>
    <!--}}} CallbackType-->
    <input id="process_vendor_id" type="hidden" value="<?php echo $vendorId ?>"/>
    <input id="auth_code" type="hidden" value="<?php echo $authCode ?>"/>
    <input id="sepaiban" type="hidden" value="">
    <input id="sepabic" type="hidden" value="">
    <input id="sepa_payment_id" type="hidden" value="37">
    <input id="result_mandate_unique" type="hidden" value="" name="result_mandate_unique">
    <input id="nnsepa_iban_confirmed" type="hidden" value="0" name="nnsepa_iban_confirmed">
    <input id="nn_sepa_merchant_validate_error_message" type="hidden" value="<?php echo $this->__('Basic parameter not valid') . '!'; ?>" />
    <input id="nn_sepa_validate_error_message" type="hidden" value="<?php echo $this->__('Your account details are invalid') . '!'; ?>" />
    <input id="result_sepa_hash" type="hidden" value="<?php echo $panhash; ?>" name="result_sepa_hash">
</ul>
<style>
.nnsepaloader {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 9999;
  background: url('<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>novalnet-loading-icon.gif') 50% 50% no-repeat;
}

.nncallbacknote {
  font-weight:bold;
  font-size:11px;
  color:gray;
  border:1px solid #BFBFBF;
  background:#FEFFBF;
  padding:10px;
  margin-top:10px;
  width:400px;
}
</style>
