<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
?>
<ul class="form-list" id="payment_form_<?php echo $code ?>" style="display:none;">
    <!--{{{ Payment Logo -->
	<?php if ($helper->getModel($code)->getNovalnetConfig('enable_payment_logo', true)): ?>
		<div>
			<a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" style="text-decoration:none;float:none;">
				<?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
					<?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . $typeCode . ".png"; ?>
					<img style="display:inline;" src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
				<?php endforeach; ?>
			</a>
		</div>
	<?php endif; ?>	
    <!--}}} Payment Logo -->
    <li>
        <?php
            echo $this->__('redirect payment description');
            echo "<br>".$this->__('Please don’t close the browser after successful payment, until you have been redirected back to the Shop');
         ?>
    </li>
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo() ?>
        </li>
    <?php endif ?>
    <?php if ($helper->getModel('novalnetCc')->getNovalnetConfig('live_mode', true) == 0): ?>
        <li>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
            </div>
        </li>
    <?php endif ?>
</ul>
