<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$assignDatahelper = Mage::helper('novalnet_payment/AssignData');
$refillValues = $assignDatahelper->_getCheckout()->getData($code);
$ccRefill = $this->getMethod()->getConfigData('cc_refill');
$creditCardSecure = $this->getMethod()->getConfigData('active_cc3d');
$refillMethod = ($refillValues != '' && $code == $refillValues->getMethod());

$billingaddres = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
?>
<fieldset class="form-list" id="fieldset_<?php echo $code ?>">
    <!--{{{ Payment Logo -->
    <div>
        <a href="<?php echo $helper->getNovalnetUrl(); ?>" target="_new" style="text-decoration:none;float:none;">
            <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . $typeCode . "_Logo.png"; ?>
                <img style="height:20px;display:inline;" src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
            <?php endforeach; ?>
        </a>
    </div>
    <!--}}} Payment Logo -->
    <!--{{{ Novalnet Cc Form -->
    <ul id="payment_form_<?php echo $code ?>" style="display:none">
        <div class="nnccloader" id='cc_loading' style='display:none;'></div>
        <li>
            <?php echo $this->__('The amount will be booked immediately from your credit card.'); ?>
        </li>
        <?php if ($this->getUserInfo()): ?>
            <li>
                <?php echo $this->getUserInfo() ?>
            </li>
        <?php endif ?>
        <?php if (Mage::helper('novalnet_payment')->getModel('novalnetCc')->_getConfigData('live_mode', true) == 0): ?>
            <li>
                <div style="font-weight:bold;color:red;font-size:12px;">
                    <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
                </div>
            </li>
        <?php endif ?>
        <li class="fields">
            <div class="field">
               <label style="float:none;" for="<?php echo $code ?>_cc_type"><?php echo $this->__('NN CC type') ?><span class="required"></span></label><br />
                 <div class="input-box">
                    <select id="<?php echo $code ?>_cc_type" onchange="ccHashCall();" class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--') ?></option>
                            <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                        <option value="<?php echo $typeCode ?>"><?php echo $typeName ?></option>
                            <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_cc_owner"><?php echo $this->__('NN CC holder') ?><span class="required"></span></label><br/>
                    <div class="input-box">
                <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $code ?>_cc_owner" autocomplete="off" onchange="ccHashCall();" value="<?php echo $billingaddres->getFirstname().' '.$billingaddres->getLastname() ?>" /></div>
            </div>
        </li>
         <li class="fields">
             <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_cc_number"><?php echo $this->__('NN CC number') ?><span class="required"></span></label><br/>
                    <div class="input-box">
                <input type="text" id="<?php echo $code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="required-entry input-text validate-cc-number validate-cc-type" autocomplete="off" onchange="ccHashCall();" onkeypress="return isNumberKey(event, true);" value="" />       </div>
            </div>
        </li>
        <li class="fields">
             <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_expiration"><?php echo $this->__('NN Expiration Date') ?><span class="required"></span></label><br />
                    <div class="input-box">
                        <div class="v-fix">
                            <select id="<?php echo $code ?>_expiration" style="width:140px;" onchange="ccHashCall();" class="required-entry">
                                <option value=""><?php echo $this->__('Month'); ?></option>
                                    <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ?>"><?php echo $v ?></option>
                                    <?php endforeach; ?>
                            </select>
                        </div>
                    <div class="v-fix" style="padding-left:5px;">
                    <select id="<?php echo $code ?>_expiration_yr" style="width:103px;" onchange="ccHashCall();" class="required-entry">
                        <option value=""><?php echo $this->__('Year'); ?></option>
                        <?php foreach ($this->getCcYears() as $k => $v): ?>
                            <option value="<?php echo $k ?>"><?php echo $v ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            </div>
        </li>
        <li class="fields">
            <div class="field">
                <label style="float:none;" for="<?php echo $code ?>_cc_cid"><?php echo $this->__('NN CVC') ?><span class="required"></span></label><br />
                 <div class="input-box">
                <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" onkeypress="return isNumberKey(event);" class="required-entry input-text validate-cc-cvn" id="<?php echo $code ?>_cc_cid" name="payment[nn_cc_cid]" style="width:3em;" autocomplete="off" /></div>
                &nbsp;
                <a href="#"><img src='<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>cvc_hint.png' border="0" style="margin-top:-15px;" alt="CCV/CVC?" id="nn_cc_hint"></a>
                <img src="<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>creditcard_cvc.jpg" style="display:none;float:left;" border="0" id="nn_cvc_hover"/>
            </div>
            </div>
        </li>
        <!--{{{ CallbackType-->
        <?php if (!$creditCardSecure && $this->isCallbackTypeCall()): ?>
            <!--{{{ PIN by Callback-->
            <?php
            if ($this->getCallbackConfigData() != 3):
                ?>
                <li>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_tel">
                            <?php
                            if ($this->getCallbackConfigData() == 2):
                                ?>
                                <?php echo $this->__('Mobile phone number'); ?>
                            <?php else: ?>
                                <?php echo $this->__('Ihre Telefon- / Mobil- Nummer'); ?>
                            <?php endif; ?>
                            <span class="required"></span></label><br/>
                        <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text validate-number" value="<?php
                        echo $ccRefill ? $helper->_getCheckout()->getData($code)->getNnCallbackTelNovalnetCc()
                                    : '';
                        ?>"/>
                    </div>
                </li>
                <li>
                    <div style="font-weight:bold;color:gray;border:1px solid #BFBFBF;font-size:11px; background:#FEFFBF; padding:10px; margin-top:10px;width:400px;">
                        <?php echo $this->__('Note for pin by sms and callback') ?>
                    </div>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_pin"><?php echo $this->__('PIN') ?><span class="required"></span></label><br/>
                        <input onkeydown="document.getElementById('<?php echo $code ?>_new_callback_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                        <input id="<?php echo $code ?>_new_callback_pin" type="checkbox" name="payment[new_callback_pin]" value="1">
                        <label style="float:none;" for="<?php echo $code ?>_new_callback_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                    </div>
                </li>
                <!--}}} PIN by Callback-->
                <!--{{{ Reply by Email-->
                <?php
            elseif ($this->getCallbackConfigData() == 3):
                ?>
                <li>
                    <div class="input-box">
                        <label style="float:none;" for="<?php echo $code ?>_callback_email"><?php echo $this->__('E-mail Address') ?><span class="required"></span></label><br/>
                        <input type="text" autocomplete="off" id="<?php echo $code ?>_callback_email" name="payment[callback_email]" title="<?php echo $this->__('Callback Email') ?>" class="input-text validate-email required-entry" value="<?php
                        echo $ccRefill ? $helper->_getCheckout()->getData($code)->getNnCallbackEmailNovalnetCc()
                                    : '';
                        ?>"/>
                    </div>
                </li>
            <?php endif ?>
            <!--}}} Reply by Email-->
        <?php endif ?>
        <!--}}} CallbackType-->
    </ul>
    <input type="hidden" id="original_vendor_id" value="<?php echo trim($this->getMethod()->_getConfigData('merchant_id', true)) ?>" />
    <input type="hidden" id="original_vendor_authcode" value="<?php echo trim($this->getMethod()->_getConfigData('auth_code', true)) ?>" />
    <input type="hidden" name="novalnet_cc_hash" id="novalnet_cc_hash" value="" />
    <input type="hidden" name="novalnet_cc_pan_hash" id="novalnet_cc_pan_hash" value="<?php echo $ccRefill ? $refillValues->getCcPanHash() : ''; ?>" />
    <input type="hidden" name="novalnet_cc_unique_id" id="novalnet_cc_unique_id" value="<?php echo $ccRefill ? $refillValues->getCcUniqueId() : ''; ?>" />
    <input type="hidden" id="nn_cc_merchant_validate_error_message" value="<?php echo $this->__('Basic parameter not valid') . '!'; ?>" />
    <input type="hidden" id="nn_cc_validate_error_message" value="<?php echo $this->__('Please enter valid credit card details') . '!'; ?>" />

</fieldset>

<style>
.nnccloader {
  position: fixed;
  left: 0px;
  top: 0px;
  width: 100%;
  height: 100%;
  z-index: 9999;
  background: url('<?php echo $helper->getNovalnetPaymentFormLogoUrl() ?>novalnet-loading-icon.gif') 50% 50% no-repeat;
}
</style>

<script type="text/javascript">
    jQuery('#nn_cc_hint').hover(function(){
     jQuery('#nn_cvc_hover').show();
    });
    jQuery('#nn_cc_hint').mouseleave(function(){
     jQuery('#nn_cvc_hover').hide();
    });
</script>
