<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
$code = Novalnet_Payment_Model_Config::NN_CC;
$helper = Mage::helper('novalnet_payment');
$paymentRequest = $helper->getCheckoutSession()->getPaymentReqData();
$payportUrl = Novalnet_Payment_Model_Config::CC_PCI_PAYPORT_URL;

// Save Transaction request data
$transactionTraces = $helper->getModelTransactionOverview();
$transactionTraces->setOrderId($paymentRequest->getOrderNo())
        ->setRequestData(serialize($paymentRequest->getData()))
        ->setCreatedDate($helper->getCurrentDateTime())
        ->save();
?> 
<div class="nnloader style='position: fixed; left: z-index: 9999;' " id="nnloader"
style="background: url('<?php echo $helper->getNovalnetPaymentFormLogoUrl(); ?>novalnet-loading-icon.gif') 70% 60% no-repeat; height: 70px; "></div>
<?php
$form = new Varien_Data_Form();
$html = '<html><body>';
echo "<form action='$payportUrl' id='$code' name='$code' method='POST' target='cc_iframe'>";
foreach ($paymentRequest->getData() as $field=>$value) {
    $form->addField($field, 'hidden', array('name'=>$field, 'value'=>$value));
}

$html.= $form->toHtml();
$html.="<iframe id='cc_iframe' scrolling='no' style='width:100%;height:450px;border:none;margin-left:-30%' name='cc_iframe' onload=document.getElementById('nnloader').style.display='none'></iframe></form>";
$html.= '<script type="text/javascript">document.getElementById("' . $code . '").submit();</script>';
$html.= '</body></html>';
echo $html;
