<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$code = $this->getMethodCode();
$helper = Mage::helper('novalnet_payment');
$billingaddress = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress();
$telephoneNumber = ($this->getCallbackConfigData() == 1 && $billingaddress->getTelephone())
           ? $billingaddress->getTelephone() : '' ;
?>
<ul class="form-list" id="payment_form_<?php echo $code ?>" style="display:none;">
    <!-- PAYMENT LOGO -->
    <div>
        <a href="<?php echo $helper->getNovalnetUrl() ?>" target="_new" style="text-decoration:none;">
            <?php $imgpath = $helper->getNovalnetPaymentFormLogoUrl() . "invoice.png"; ?>
            <img src="<?php echo $imgpath ?>" alt="<?php echo $this->getMethod()->getConfigData('title') ?>" title="<?php echo $this->getMethod()->getConfigData('title') ?>" />
        </a>
    </div>
    <!-- PAYMENT LOGO -->
    <!--{{{ PAYMENT DESCRIPTION  -->
    <li>
        <?php echo $this->__('Invoice/Prepayment payment description') ?>
    </li>
    <?php if ($this->getUserInfo()): ?>
        <li>
            <?php echo $this->getUserInfo() ?>
        </li>
    <?php endif ?>
    <?php if ($this->getMethod()->getNovalnetConfig('live_mode', true) == 0): ?>
        <li>
            <div style="font-weight:bold;color:red;font-size:12px;">
                <?php echo $this->__('Please Note: This transaction will run on TEST MODE and the amount will not be charged') ?>
            </div>
        </li>
    <?php endif ?>
    <!--}}} PAYMENT DESCRIPTION  -->
    <!--{{{ CallbackType-->
    <?php if ($this->isCallbackTypeCall()): ?>
        <!--{{{ PIN by Callback-->
        <?php if ($this->getCallbackConfigData() != 3): ?>
            <li>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                <label for="<?php echo $code ?>_callback_tel" class="required"><em>*</em>
                    <?php if ($this->getCallbackConfigData() == 2): ?>
                        <?php echo $this->__('Mobile phone number'); ?>
                    <?php else: ?>
                        <?php echo $this->__('NN Mobile Number'); ?>
                    <?php endif; ?>
                </label>
                <div class="input-box">
                    <input type="text" value="<?php echo $telephoneNumber; ?>" id="<?php echo $code ?>_callback_tel" name="payment[callback_tel]" title="<?php echo $this->__('Callback') ?>" class="required-entry input-text validate-number" />
                </div>
            </li>
            <li>
                <div class="nncallbacknote">
                    <?php echo $this->__('Note for pin by sms and callback') ?>
                </div>
                <label for="<?php echo $code ?>_callback_pin" class="required"><em>*</em><?php echo $this->__('PIN') ?></label>
                <div class="input-box">
                    <input onkeydown="document.getElementById('<?php echo $code ?>_new_callback_pin').checked = false;" size="4" type="text" id="<?php echo $code ?>_callback_pin" name="payment[callback_pin]" title="<?php echo $this->__('Callback') ?>" class="input-text" /><br/>
                    <input id="<?php echo $code ?>_new_callback_pin" type="checkbox" name="payment[new_callback_pin]" value="1">
                    <label style="float:none;" for="<?php echo $code ?>_new_callback_pin"><?php echo $this->__('Forgot PIN? [New PIN Request]') ?></label>
                </div>
            </li>
            <!--}}} PIN by Callback-->
            <!--{{{ Reply by Email-->
        <?php elseif ($this->getCallbackConfigData() == 3): ?>
            <li>
                <label for="<?php echo $code ?>_callback_email" class="required"><em>*</em><?php echo $this->__('E-mail Address') ?></label>
                <div class="input-box">
                    <input type="text" value="<?php echo $billingaddress->getEmail(); ?>" id="<?php echo $code ?>_callback_email" name="payment[callback_email]" title="<?php echo $this->__('Callback Email') ?>" class="input-text validate-email required-entry" />
                </div>
            </li>
        <?php endif ?>
        <!--}}} Reply by Email-->
    <?php endif ?>
    <!--}}} CallbackType-->
</ul>
<style>
.nncallbacknote {
  font-weight:bold;
  font-size:11px;
  color:gray;
  border:1px solid #BFBFBF;
  background:#FEFFBF;
  padding:10px;
  margin-top:10px;
  width:400px;
}
</style>
