<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$_order = $this->getOrder();
$grandTotal = $_order->getBaseGrandTotal();
$payment = $_order->getPayment();
$paymentname = $payment->getMethodInstance()->getCode();
$paymentObj = $payment->getMethodInstance();
$data = unserialize($payment->getAdditionalData());
$parentTid =   isset($data['NnTid']) ? $data['NnTid'] : '';
$sepaparentTid =  isset($data['NnSepaParentTid']) ? $data['NnSepaParentTid'] : '';
?>
<div>
    <div id="order-messages">
        <?php echo $this->getChildHtml('order_messages') ?>
    </div>
    <?php echo $this->getChildHtml('order_info') ?>
    <input type="hidden" name="order_id" value="<?php echo $_order->getId() ?>"/>
    <?php if ($_order->getIsVirtual()): ?>
        <div class="box-right">
        <?php else: ?>
            <div class="box-left">
            <?php endif; ?>
            <!--Payment Method-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
                </div>
                <fieldset>
                    <?php echo $this->getPaymentHtml() ?>
                    <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $_order->getOrderCurrencyCode()) ?></div>
                </fieldset>
            </div>
            <?php
            $sepapayment = array(
                Novalnet_Payment_Model_Config::NN_SEPA,
            );
            $invoicepayment = array(
                Novalnet_Payment_Model_Config::NN_PREPAYMENT,
                Novalnet_Payment_Model_Config::NN_INVOICE
            );

            //$paymentname
            $helper = Mage::helper('novalnet_payment');
            $checkTidExist = $sepaparentTid ? $sepaparentTid : $parentTid;
            if (!$checkTidExist) {
                $checkTidExist = $payment->getLastTransId();
            }
            if (preg_match("/refund/i", $checkTidExist)) {
                $checkTidExist = str_replace("-refund",'',$checkTidExist);
            }

            $getTransactionStatus = $helper->loadTransactionStatus($checkTidExist);
            $status = $getTransactionStatus->getTransactionStatus();
            $invoice = $_order->getInvoiceCollection()->getFirstItem();
            $paid = $invoice->getState();

            $amount = $helper->getAmountCollection($_order->getId(), 1, 0);
            $amount = !$amount ? $amount : $grandTotal;
            $amount = $helper->getFormatedAmount($amount);

            if (in_array($paymentname, array_merge($sepapayment,$invoicepayment))) {
                $statusCall = $paymentObj->doNovalnetStatusCall($checkTidExist,$payment);
            }

            $amount = '';
            $date = '';

            if ($status == 99 && $getTransactionStatus->getTransactionStatus() && in_array($paymentname, $sepapayment)
                    && $_order->canInvoice()) {
                        $amount = $statusCall->getAmount();
                ?>
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Change the amount') ?></h4>
                    </div>
                    <fieldset>
                        <br />
                        <div><?php echo $this->__('Novalnet transaction amount') ?>:&nbsp;<input class="validate-date required-entry" type="text" id="amount_changed" name="amount_changed" value="<?php echo $amount; ?>" onkeypress="return novalnetAllowNumeric(event)"; style="width:4em" /> &nbsp;&nbsp;
                            <button type="button" title="<?php echo $this->__('Amount Changed button') ?>" class="button" onclick="amount_changed('<?php
                            echo Mage::helper('adminhtml')->getUrl('*/novalnetpayment_sales_order/amountupdate', array(
                                'order_id' => $_order->getId()))
                            ?>', 2,'<?php echo $this->__('Enter the valid amount'); ?>');"><span><span><?php echo $this->__('Amount Changed button') ?></span></span></button><br /><br />

                        </div>
                        <br />
                    </fieldset>
                </div>
                <?php
            } else if ($status == 100 && in_array($paymentname, $invoicepayment)
                    && ($paid == 1 || !$paid)) {
                        $amount = $statusCall->getAmount();
                        $date = $statusCall->getInvoiceDueDate();
                ?>
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Novalnet Amount Changed') ?></h4>
                    </div>
                    <fieldset>
            <table>
            <tr><td><span style='width:50%;'><?php echo $this->__('Novalnet transaction amount') ?>:&nbsp;</span></td>
            <td><input class="validate-date required-entry" type="text" id="amount_changed" name="amount_changed" value="<?php echo $amount; ?>" onkeypress="return novalnetAllowNumeric(event)"; style="width:6em" /></td></tr>

                            <tr><td><?php echo $this->__('Invoice Due Date') ?>:</td><td><input class="validate-date" type="text" id="invoice_duedate" name="invoice_duedate" value="<?php echo $date; ?>" style="width:6em" /></td>
                            </tr>

            <tr><td colspan=2>
            <button type="button" title="<?php echo $this->__('Amount Changed button') ?>" class="button" onclick="amount_changed('<?php
                            echo Mage::helper('adminhtml')->getUrl('*/novalnetpayment_sales_order/amountupdate', array(
                                'order_id' => $_order->getId()))
                            ?>', '<?php echo $paid; ?>','<?php echo $this->__('Enter the valid amount'); ?>','<?php echo $this->__('Enter the amount or invoice duedate'); ?>','<?php echo $this->__('Invoice duedate is invalid'); ?>','<?php echo $this->__('Invalid due date'); ?>');"><span><span><?php echo $this->__('Amount Changed button') ?></span></span></button></td></tr>
            </table>
                    </fieldset>
                </div>
            <?php } ?>
            <?php
            $countofCollection = $helper->getAmountCollection($_order->getId(), NULL, NULL);
            if ($countofCollection > 0) {
                ?>
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-products"><?php echo $helper->__('Updated Amount') ?></h4>
                    </div>
                    <fieldset>
                        <div>
                            <?php
                            $updateCollection = explode('<br>', $helper->getAmountCollection($_order->getId(), 1, 1));
                            echo $this->__('The transaction amount %s has been updated successfully on %s', '('.$updateCollection[0] . ' ' .  $_order->getOrderCurrencyCode() . ')', $updateCollection[1]);
                            ?>
                        </div>
                        <br />
                    </fieldset>
                </div>
            <?php } ?>
        </div>
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box-right">
                <!--Shipping Method-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
                    </div>
                    <fieldset>
                        <?php if ($_order->getTracksCollection()->count()) : ?>
                            <a href="#" id="linkId" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>', 'trackorder', 'width=800,height=600,resizable=yes,scrollbars=yes')" title="<?php echo $this->__('Track Order') ?>"><?php echo $this->__('Track Order') ?></a>
                            <br/>
                        <?php endif; ?>
                        <?php if ($_order->getShippingDescription()): ?>
                            <strong><?php echo $this->escapeHtml($_order->getShippingDescription()) ?></strong>

                            <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                                <?php $_excl = $this->displayShippingPriceInclTax($_order); ?>
                            <?php else: ?>
                                <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                            <?php endif; ?>
                            <?php $_incl = $this->displayShippingPriceInclTax($_order); ?>

                            <?php echo $_excl; ?>
                            <?php
                            if ($this->helper('tax')->displayShippingBothPrices()
                                    && $_incl != $_excl):
                                ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                        <?php else: ?>
                            <?php echo $this->helper('sales')->__('No shipping information available'); ?>
                        <?php endif; ?>
                    </fieldset>
                </div>
            </div>
        <?php endif; ?>
        <div class="clear"></div>
        <?php echo $this->getGiftOptionsHtml() ?>
        <div class="clear"></div>
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>
            </div>
        </div>
        <?php echo $this->getItemsHtml() ?>
        <div class="clear"></div>

        <div class="box-left">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
                </div>
                <fieldset><?php echo $this->getChildHtml('order_history') ?></fieldset>
            </div>
        </div>
        <div class="box-right entry-edit">
            <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Order Totals') ?></h4></div>
            <div class="order-totals"><?php echo $this->getChildHtml('order_totals') ?></div>
        </div>
        <div class="clear"></div>
    </div>

    <?php echo $this->getChildHtml('popup_window'); ?>
    <script type="text/javascript">
        //<![CDATA[
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function(element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0, 30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }
        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);

        function novalnetAllowNumeric(evt) {

        var charCode = (evt.which) ? evt.which : evt.keyCode

        if((charCode == 35 || charCode == 36 ||charCode == 37
          || charCode == 39) && evt.shiftKey == false) {
            return true;
        }
        else if((evt.ctrlKey == true && charCode == 114)|| charCode == 116) {
          return true;
        }
        else if(charCode > 31 && (charCode < 48 || charCode > 57)) {
            return false;
        }else{
        return true;
        }
         }

        function reformatDate(dateStr)
        {
        dArr = dateStr.split("-");  // ex input "2010-01-18"
        return dArr[2]+ "." +dArr[1]+ "." +dArr[0]; //ex out: "18/01/10"
        }

        function amount_changed(url, one,lang,lang1,lang2,lang3) {

            var amountchanged = document.getElementById('amount_changed').value;
            var paymentcode = '<?php echo $paymentname; ?>';

            if (one == 1 || paymentcode == 'novalnetPrepayment') {
                var invoice_duedate = document.getElementById('invoice_duedate').value;
                invoicedate = invoice_duedate.length;
                var rx_date_pattern = /^(\d{4})(\/|-)(\d{1,2})(\/|-)(\d{1,2})$/;
                var dt_array = invoice_duedate.match(rx_date_pattern);
                var dt_month = dt_array[3];
                var dt_day   = dt_array[5];
                var dt_year  = dt_array[1];
            }


            if ((one == 1 || paymentcode == 'novalnetPrepayment') && !invoice_duedate && !amountchanged) {
                alert(lang1);
                return false;
            }
            //return false;
            if (!amountchanged || amountchanged <= 0 || isNaN(amountchanged)) {
                alert(lang);
                return false;
            }
            if ((one == 1 || paymentcode == 'novalnetPrepayment') && invoice_duedate && !invoice_duedate.match(/^[0-9]{4}\-(0[1-9]|1[012])\-(0[1-9]|[12][0-9]|3[01])/)) {
                Translator.add('Invoice duedate is invalid', '<?php echo $this->__('Invoice duedate is invalid'); ?>');
                alert(Translator.translate(lang2));
                return false;
            } else if ((dt_month==4 || dt_month==6 || dt_month==9 || dt_month==11) && dt_day ==31) {
                Translator.add('Invalid due date', '<?php echo $this->__('Invalid due date'); ?>');
                alert(Translator.translate(lang3));
                return false;
            } else if (dt_month == 2) {
                var is_leap = (dt_year % 4 == 0 && (dt_year % 100 != 0 || dt_year % 400 == 0));
                if (dt_day > 29 || (dt_day ==29 && !is_leap)) {
                    Translator.add('Invalid due date', '<?php echo $this->__('Invalid due date'); ?>');
                    alert(Translator.translate(lang3));
                    return false;
                }
            } else if ((one == 1 || paymentcode == 'novalnetPrepayment') && invoicedate > 10) {
                alert(Translator.translate(lang2));
                return false;
            }

            if (invoice_duedate == undefined) {
                invoice_duedate = '';
            }
            <?php
            $currencySymbol = Mage::app()->getLocale()->currency($_order->getOrderCurrencyCode())->getSymbol();
            ?>
            var nconfirm = '<?php echo (!in_array($paymentname, $invoicepayment)) ? $this->__('Are you sure you want to change the order amount?') : $this->__('Are you sure you want to change the order amount or due date?'); ?>';
            if (confirm(nconfirm) == true) {
                window.location.href = url + "amount_change/" + amountchanged + "/invoice_duedate/" + invoice_duedate;
            } else {
                return false;
            }
        }

        //]]>
    </script>
    <script type="text/javascript">// <![CDATA[
        if (document.getElementById('invoice_duedate') != undefined) {
            Calendar.setup({
                inputField: 'invoice_duedate',
                ifFormat: '%Y-%m-%d',
                button: 'date_to_trig',
                align: 'Bl',
                singleClick: true
            });
        }
    // ]]></script>
