<div class="clear"></div>
         <div class="box-left">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('SEPA Mandate Signed') ?></h4>
            </div>
        </div>
        <div class="grid np">
            <fieldset>
				<br />
                <div><?php echo $this->__('Date') ?>:&nbsp;<input class="input-text no-changes required-entry" type="text" id="sepa_mandate_sign" name="sepa_mandate_sign" value="<?php echo $this->getFilter('report_from') ?>" style="width:5em" /> &nbsp;&nbsp;
                <button style="" onclick="setLocation('')" class="scalable go" type="button" title="SEPA Mandate Signed" id="id_b4e98b73dc3651d37e7548172e49c4d4"><span><span><span>Mandate Signed</span></span></span></button>
                </div>
                <br />
            </fieldset>
        </div>
