<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the Paymentmodule of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script usefull a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Novalnet AG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$data = $this->getTransaction();
?>
<input type="hidden" name="order_id" value="<?php echo $data->getOrderId() ?>"/>

<div class="box-left">
    <!--Novalnet Order Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Order Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Store-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getStoreId() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Order-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getOrderId() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Tranaction-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getTransactionNo() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Transaction-Status') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getTransactionStatus() ?></strong>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('NC No') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getNcNo() ?></strong>
                    </td>
                </tr>				
                <tr>
                    <td class="label">
                        <label><?php echo $this->helper('novalnet_payment')->__('Customer-ID') ?></label>
                    </td>
                    <td class="label">
                        <strong><?php echo $data->getCustomerId() ?></strong>
                    </td>
                </tr>
            </table>
        </div>
    </div>	
</div>
<div class="box-right">
    <!--Novalnet Order Shop Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Shop Information') ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><?php echo $this->helper('novalnet_payment')->__('Shop URL') ?></label>
                </td>
                <td class="label">
                    <strong><?php echo $data->getShopUrl() ?></strong>
                </td>
            </tr>
        </table>
    </div>

    <!--Novalnet Order Additional Information-->
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Additional Information') ?></h4>
        </div>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><?php echo $this->helper('novalnet_payment')->__('Additional Data') ?></label>
                </td>
                <td class="label">
                    <strong><?php echo $data->getAdditionalData() ?></strong>
                </td>
            </tr>
        </table>
    </div>
</div>