<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * Part of the payment module of Novalnet AG
 * https://www.novalnet.de
 * If you have found this script useful a small
 * recommendation as well as a comment on merchant form
 * would be greatly appreciated.
 *
 * @category   Novalnet
 * @package    Novalnet_Payment
 * @copyright  Copyright (c) Novalnet AG. (https://www.novalnet.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
$transactioOverviewCollection = $this->getTransactionOverview();
$i = 1;
foreach ($transactioOverviewCollection as $transactioOverviewId => $data) {
    ?>
    <?php if ($i == 1): ?>
        <div class="box-left">
            <!--Novalnet Order Information-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Order Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td class="label">
                                <label><?php echo $this->helper('novalnet_payment')->__('Store-ID') ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $data->getStoreId() ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label><?php echo $this->helper('novalnet_payment')->__('Order-ID') ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $data->getOrderId() ?></strong>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>

        <div class="box-right">
            <!--Novalnet Order Information-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method"><?php echo Mage::helper('novalnet_payment')->__('Novalnet Additional Information') ?></h4>
                </div>
                <div class="fieldset">
                    <table cellspacing="0" class="form-list">
                        <tr>
                            <td class="label">
                                <label><?php echo $this->helper('novalnet_payment')->__('Customer-ID') ?></label>
                            </td>
                            <td class="label">
                                <strong><?php echo $data->getCustomerId() ?></strong>
                            </td>
                        </tr>
                        <tr>
                            <td class="label">
                                <label><?php echo $this->helper('novalnet_payment')->__('Shop URL') ?></label>
                            </td>
                            <td style="word-break:break-word;">
                                <strong><?php echo $data->getShopUrl() ?></strong>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <?php
    endif;
    $i++;
    ?>

    <!-- Novalnet API Data -->
    <div class="box-left" style="clear:both;">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method" style="float:none;">
                    <?php echo Mage::helper('novalnet_payment')->__('Novalnet Request Data') ?>
                    <span style="float:right;"><?php echo 'TID : ' . $data->getTransactionId() ?></span>
                </h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list" width="100%">
                    <tr>
                        <td class="label">
                            <label><?php echo $this->helper('novalnet_payment')->__('Request Data') ?></label><br/>
                            <?php
                            $getrequestData = unserialize($data->getRequestData());
                            if ($getrequestData) {
                                ?>
                                <div style="height:250px;overflow:scroll;width:470px;">
                                    <strong> <?php
                                        echo "<pre>";
                                        print_r($getrequestData);
                                        echo "</pre>";
                                        ?> </strong>
                                </div>
                            <?php } ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="box-right">
        <div class="entry-edit">
            <div class="entry-edit-head">
                <h4 class="icon-head head-payment-method" style="float:none;">
                    <?php echo Mage::helper('novalnet_payment')->__('Novalnet Response Data') ?>
                    <span style="float:right;"><?php echo 'TID : ' . $data->getTransactionId() ?></span>
                </h4>
            </div>
            <div class="fieldset">
                <table cellspacing="0" class="form-list" width="100%">
                    <tr>
                        <td class="label">
                            <label><?php echo $this->helper('novalnet_payment')->__('Response Data') ?></label><br>
                            <?php
                            $getresponseData = unserialize(base64_decode($data->getResponseData()));
                            if ($getresponseData) {
                                ?>
                                <div style="height:250px;overflow:scroll;width:470px;">
                                    <strong> <?php
                                        echo "<pre>";
                                        print_r($getresponseData);
                                        echo "</pre>";
                                        ?> </strong>
                                </div>
                            <?php } ?>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
<?php } ?>
